### ISSUE TITLE
Support installing custom PHP extensions without forking the buildpack and copying the whole bucket

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#104]
This is something I already discussed with @dzuelke but I cannot find an issue tracking this, so here it goes.

The goal is to be able to install custom PHP extensions which are not provided by the buildpack itself.
There is 2 ways to provide this:

- easy (but slow) one: run pecl (or pickle) for these extensions
- faster (but more complex) one: allow apps to specify a place where the compiled extensions are available and then simply download them. This would also involve documenting the process to compile extensions for usage on heroku (and it needs to be able to support extensions needing a binding to an external lib btw)

**Comment by martijngastkemper** [comment]
:+1:

**Comment by dzuelke** [comment]
Yes, working on all of this at the moment. ETA is currently several weeks. It's gonna be a few "waves" of features, starting with changes to how configs are bundled, then support for versioned extensions, and finally the ability for multiple S3 repositories with binaries that are searched through sequentially, so you can have your own bucket of custom extensions (and there will be docs eventually of course).

**Comment by slbmeh** [comment]
I just made a change to the compile in my fork to handle solution number 2.  It's in pr #111

**Comment by slbmeh** [comment]
I just made a change to the compile in my fork to handle solution number 2.. it's in #110

**Comment by stof** [comment]
@dzuelke any news ?

**Comment by stof** [comment]
@dzuelke do you have any news about that ?

**Comment by auro1** [comment]
status?

**Comment by dzuelke** [comment]
All the necessary base work has been released for a few weeks. I am currently testing custom buckets and extension repos with someone. Seems to work really well. Should be able to roll it out next week.

**Comment by NielsJanssen** [comment]
Exciting stuff, whats the status of this atm?

**Comment by gboudreau** [comment]
@dzuelke Any news on this?

**Comment by dzuelke** [comment]
It's all done and working. Just need to write docs and roll it out.

**Comment by dzuelke** [comment]
(today!)

**Comment by dzuelke** [comment]
https://github.com/heroku/heroku-buildpack-php/blob/develop/README.md is the new README, https://github.com/heroku/heroku-buildpack-php/blob/develop/support/build/README.md has initial build info (look through some formulae, such as "php" and "blackfire", for inspiration), and a crude Dockerfile lets you build without Heroku: https://github.com/heroku/heroku-buildpack-php/blob/develop/support/build/_docker/README.md

I plan on merging to master this afternoon. Feedback welcome. The `develop` branch of the buildpack also runs on this very latest infrastructure (where configs are bundled with packages, packages can hook into `export` and `.profile.d`, and even Apache and Nginx are installed as a custom Composer package).

I fully expect @stof to start running an unofficial but impressive repository of exotic extensions soon ;)

**Comment by dzuelke** [comment]
Not going to merge and release until at least tomorrow. I want to figure out #146 first; worst case I need to overhaul the whole package naming/handling :<

**Comment by dzuelke** [comment]
Now released. Enjoy; feedback welcome! :)
