### ISSUE TITLE
Amqp extension support

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#107]
it would be great to support the amqp extension, to allow easier usage of RabbitMQ on heroku (the userland implementation is not good. It is leaking and does not implement prefetching properly)

**Comment by dzuelke** [comment]
Agreed; it's on my list, just haven't tackled it yet because of the `libamqp` dep. Soon!

**Comment by stof** [comment]
@dzuelke now that deps are resolved with composer too, could deps like libamqp be installed the same way, by creating ``heroku-sys/libamqp`` and making it a dependency of each ``heroku-sys/ext-amqp`` package ?

**Comment by dzuelke** [comment]
Potentially, although I'm not sure what the benefit would be; you could ship libamqp bundled with ext-amqp instead (like the buildpack does with e.g. the memcached extension).

I am currently negotiating with those responsible for the cedar stack images to include libamqp ;) I'd really rather not maintain all those PECL extensions with their different libraries by hand, it's just a massive burden (and occasionally a security consideration too).

Wouldn't you be interested in running an S3 bucket with a few unofficial extensions @stof? ;)

**Comment by stof** [comment]
@dzuelke I am, which is why I'm looking into this.

**Comment by stof** [comment]
> I am currently negotiating with those responsible for the cedar stack images to include libamqp ;)

That would be awesome (in which case ext-amqp could maybe even become part of the extensions supported in the core)

**Comment by dzuelke** [comment]
Yeah once libamqp would be in cedar for sure I'd maintain it officially.

**Comment by stof** [comment]
note that compiling recent versions of ext-amqp depends on an uptodate version of librabbitmp, not on the old version available in Ubuntu 14.04

**Comment by dzuelke** [comment]
Eww.

**Comment by stof** [comment]
see https://github.com/pdezwart/php-amqp#requirements

Ubuntu 14.04 ships with librabbitmq 0.4.1 released in August 2013.

And older versions of ext-amqp supporting this very old versions are not compatible with PHP 7 (support is added in 1.7.0-alpha) and suffer from bugs (impacting the connection to RabbitMQ provided by the CloudAMQP addon btw)

**Comment by stof** [comment]
@dzuelke have you any news from the cedar stack team regarding this ?

**Comment by dzuelke** [comment]
Oh sorry I thought you had given the answer yourself after pointing out that the version that ships with 14.04 is too old anyway :/

**Comment by stof** [comment]
well, have you asked them though ? not all cedar packages are using the version available in Ubuntu 14.04 (Ubuntu 14.04 contains postgresql-client-9.3, not postgresql-client-9.5 for instance, but I haven't checked the full list to compare it with ubuntu versions to build an exhaustive list)

**Comment by dzuelke** [comment]
Yeah, not happening for now, at least not for cedar-14 (maybe Ubuntu 16.04 will bring a more suitable version, and we'll then revisit what packages to include in the stack image(s)).

Postgres is the sole exception since we offer that as a service, and older clients cannot access newer servers. But that's also not maintained by hand, but from an upstream Ubuntu repo.

**Comment by stof** [comment]
Closing because the support is provided in https://github.com/Incenteev/heroku-php-exts now

**Comment by dzuelke** [comment]
Reopening to track adoption for new `heroku-16` stack.

**Comment by stof** [comment]
Well, wouldn't it be better to open an issue on my repo instead ?

**Comment by stof** [comment]
I opened https://github.com/Incenteev/heroku-php-exts/pull/2 about the progress on the heroku-16 stack support. I will merge it once the building is working

**Comment by dzuelke** [comment]
Sorry, misleading phrasing. I'd like to provide that ext out of the box on Heroku for the new stack now that Ubuntu has a suitable library version of `librabbitmq`.

**Comment by stof** [comment]
Closing this, as it is not supported in the buildpack itself.

**Comment by dzuelke** [comment]
s/not/now ;)

Yes, sorry for never closing this; it's been supported since v121 in March 2017...
