### ISSUE TITLE
Update New Relic version

### ISSUE THREAD

**Issue by mattions** [heroku/heroku-buildpack-php#108]
Hi,
latest newrelic version installed by the buildpack is: `4.19.0.90 ("drepanis") ("fb39bb6d34a3f0a7407ab2e3b0786d7d346f4b25")` while latest agent available is: `4.21.0.97` https://discuss.newrelic.com/t/php-agent-4-21-0-97-release-notes/24617

Do you think would be possible to update?

**Comment by dzuelke** [comment]
Yea; rolling out today or tomorrow, already have it done in development.

**Comment by dzuelke** [comment]
4a4910111d06d2f2da1ca4358e7d475b6134cf9f
