### ISSUE TITLE
Logs from Php-fpm not available

### ISSUE THREAD

**Issue by mattions** [heroku/heroku-buildpack-php#112]
Hi,

I can't see the log in the `/tmp` directory.
I do get the logs from nginx, but the one from php-fpm are only showing up at the start

```
       [16-May-2015 10:34:59] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
       [16-May-2015 10:34:59] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
```

I'm trying to run a wordpress instantiation on dokku, and everything goes, however when I try to use the publicize plugins I get this error:

```
Something which should never happen, happened. Sorry about that. If you try again, maybe it will work.

Error code: -32601
```

I know this a quite long shot, however I was wondering if the php are merged with nginx and if so, why the files where they supposed to be written do not get created.

For reference these are the locations I have checked:

```logs=( "/tmp/heroku.php-fpm.$PORT.log" "/tmp/heroku.php-fpm.www.$PORT.log" "/tmp/heroku.nginx_access.$PORT.log" )```

Any pointer would be handy.

Best,
Michele

**Comment by dzuelke** [comment]
The PHP errors will end up in the FPM log. But your issue is that Wordpress is set up to write its logs to a file. You can use the `-l` switch of the boot script to tail an additional log file to the log stream, or you change/configure Wordpress to write to `php://stderr` instead of a log file.
