### ISSUE TITLE
Configuring the build directory

### ISSUE THREAD

**Issue by ged15** [heroku/heroku-buildpack-php#116]
Hi!

We have the following directory structure in our Git repo:
```
/
-- backend
  | src/
  | composer.json
  | composer.lock
  | etc.
-- frontend
  | <static files>
```

The buildpack makes the assumption that the `composer.json` file is in the root. Is there a way to make the buildpack/ platform look at the `backend/` dir.? Currently it just uses the `BUILD_DIR` passed by the platform. Is there a way to modify this behavior or do we need to fork the buildpack?

**Comment by martijngastkemper** [comment]
```composer --working-dir "backend"``` ([docs](https://getcomposer.org/doc/03-cli.md#global-options)) is doing what you want, but you need to change the buildpack to add that flag. The easiest solution without changing the buildpack is moving the composer.* files to the root and set COMPOSER_VENDOR_DIR to "backend/vendor" ([docs](https://getcomposer.org/doc/03-cli.md#composer-vendor-dir)].

**Comment by dzuelke** [comment]
Indeed `composer.json` needs to be at the root of your project. It's a PHP application, after all.

You don't even need to use `COMPOSER_VENDOR_DIR`; just have a `config` section in your `composer.json` where you set `vendor-dir` to your desired destination.

In general, though, I don't see a reason why your dependencies can't live at the root of the project. You don't check them into Git anyway, so they're not "in the way" either.

**Comment by ged15** [comment]
Totally agree that `composer.json` belongs in the root of the project. When using a monolithic repo, Git repo != app, though :)
So, I guess, the thing in question here is Heroku's assumption that repo === app.
I can understand this assumption, although this renders Heroku unusable in situations like mine. Or am I missing something?

**Comment by dzuelke** [comment]
Yeah, that is the assumption, and it's actually not hard/impossible to do for most users to split their application into more manageable parts. Making this configurable would mean changes in much more than just a single location; build time, runtime (boot scripts), potentially even web server configs (what are configured docroots etc now relative to?).

I wonder though what's stopping you from moving `composer.*` to the top level?

**Comment by ged15** [comment]
I actually solved everything by moving the composer files to the root. This, however, makes me modify my source code structure (location of composer files at least) due to Heroku's assumptions. Not really a fan of that, but this trade-of is small considering how much work Heroku saves me.
