### ISSUE TITLE
GMP functions support

### ISSUE THREAD

**Issue by josecelano** [heroku/heroku-buildpack-php#117]
Hi, how could I add GMP support? http://php.net/manual/en/book.gmp.php

Should I do something like this?:

http://www.sitepoint.com/install-custom-php-extensions-heroku/

or is there an easy way to do it?

Thanks

**Comment by martijngastkemper** [comment]
README.md contains a section called Development. With that you can easily fork this buildpack and add your own extensions. There are some PRs with custom extensions. You can look at them for inspiration: #58, #73 or #58.

**Comment by martijngastkemper** [comment]
I made a mistake. It's not an extensions. Nevertheless you can change the PHP compile flags in your own Buildpack.

**Comment by josecelano** [comment]
Thanks @martijngastkemper That's why I open this issue. I was taking a llot into the PRs you told me but I reached the same conclusion but I am not sure if I only have to add a flag here https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/php#L44
or I also have to  download and compile the library as shown in the link http://www.sitepoint.com/install-custom-php-extensions-heroku/
Could you point me to a sample or more info I only have found that blog post.

**Comment by martijngastkemper** [comment]
You need to compile GMP library. The ssh2 extension has [libssh2](https://github.com/martijngastkemper/heroku-buildpack-php/blob/ext-ssh/support/build/libraries/libssh2) as a dependency. Make sure you use the right prefix.

You have to add the dependency to https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/php#L3. Then add --with-gmp=${OUT_PREFIX} to L44.

I think that should do the trick.

**Comment by josecelano** [comment]
thanks @martijngastkemper I have created a fork and added what you told me:

https://github.com/heroku/heroku-buildpack-php/compare/master...josecelano:master

now I am going to try a deploy with this builpack.

**Comment by josecelano** [comment]
It does not work and I do not know how to get logs.

````

**Comment by djtarazona** [comment]
Did you modify the compile script to pull the binaries from your S3 bucket?

https://github.com/heroku/heroku-buildpack-php/blob/master/bin/compile#L63

**Comment by martijngastkemper** [comment]
Regarding this line ``WARNING: Unknown extension gmp (composer.lock), install may fail!``, did you add it as an extension to composer.json? GMP is not an extension.

**Comment by martijngastkemper** [comment]
You can try to add an empty ext-gmp.ini file to ``conf/php/conf.d``. See: https://github.com/heroku/heroku-buildpack-php/blob/master/bin/compile#L11

**Comment by martijngastkemper** [comment]
Additionally try to add ``extension=gmp.so`` to that file. Maybe there's an extual .so file in the extension directory.

**Comment by josecelano** [comment]
@djtarazona I ran this command

```shell
eroku.com/php-client-sample.git'
 heroku buildpacks:set https://github.com/josecelano/heroku-buildpack-php.git -a php-client-sample
```

It is supposed you can change the buildpack for an application using the CLI:
https://devcenter.heroku.com/articles/third-party-buildpacks#using-a-custom-buildpack

**Comment by dzuelke** [comment]
Will work on this soon. Should be possible but needs a few tweaks to the build infrastructure. Thanks for your patience!

**Comment by abgit** [comment]
@dzuelke , thanks for your time on this.
GNU Multiple Precision ```ext-gmp``` is a very important php extension used by a lot of packages and growing every day.

**Comment by dzuelke** [comment]
I'm aware!

**Comment by abgit** [comment]
any ETA for `ext-gmp` support ?

**Comment by abgit** [comment]
@dzuelke , any ETA for ext-gmp support ?

**Comment by dzuelke** [comment]
I'm partially on vacation next week, so I'd guess around two weeks. It really is coming soon. It's not simply a matter of `--with-gmp=shared` because dev packages on the cedar-14 stack are missing.

**Comment by chris41188** [comment]
Looking forward to this! please let me know if/when it is live christian@mandelduck.com

**Comment by abgit** [comment]
+1 on this 

> Looking forward to this! please let me know if/when it is live christian@mandelduck.com
> 
> —
> Reply to this email directly or view it on GitHub.
> 

O conteúdo desta mensagem de correio eletrónico e seus anexos é confidencial e de uso reservado.
Se não é o destinatário, não a guarde, não a reenvie a terceiros, nem faça qualquer uso da informação nela contida. Por favor, apague-a e informe de imediato o remetente. A Internet não garante a confidencialidade e a entrega correta de mensagens de correio eletrónico pelo que não aceitamos responsabilidade por danos causados pela receção incorreta desta mensagem.
Apesar de esta mensagem ter sido verificada pelo nosso sistema de antivírus, não podemos garantir que não contenha vírus informáticos e não aceitamos qualquer responsabilidade por danos causados por vírus que possam estar contidos nesta mensagem.

This e-mail and related attachments contain confidential and legally privileged information.
If you are not the intended recipient you must not keep it in your records or forward it to any third parties, nor use the information contained in it. Please delete it and notify by return Email. Internet email does not guarantee the confidentiality or the proper receipt of messages sent so we decline any liability for damages caused by improper receipt of this message.
Our own virus checking system has swept this e-mail and its attachments. However, we cannot guarantee that it is vírus-free and cannot take responsibility for any virus which may be present.

**Comment by abgit** [comment]
@dzuelke , any ETA for `ext-gmp`?

**Comment by dzuelke** [comment]
Should be done next week @abgit. Thank you for your patience!

**Comment by chris41188** [comment]
Excited! Currently running a separate ruby app just to do the functions php can't

**Comment by abgit** [comment]
Any news on `ext-gmp` support, @dzuelke ?

**Comment by abgit** [comment]
@dzuelke , can you take some time on `ext-gmp`?

**Comment by abgit** [comment]
Sadly, `ext-gmp` was not included in heroku's ["February 2016 PHP runtimes and extensions update"](https://devcenter.heroku.com/changelog-items/823).
Missing `ext-gmp` is really preventing some projects to get into production on heroku.

@dzuelke, any chance to get it on next heroku php extension update?

**Comment by dzuelke** [comment]
I understand you're eager to use it, @abgit, but there is some prerequisite work that needs doing first. Please bear with me a bit longer.

**Comment by abgit** [comment]
I (and everyone else) can wait for sure. My biggest concern is.. expectation.
Is there any chance to get an effective eta?

**Comment by martijngastkemper** [comment]
I agree with @abgit. It's the same with #58. An accurate eta would be very nice. Nevertheless I appreciate the hard work on this buildpack, it's much better then before Heroku PHP support.
