### ISSUE TITLE
Apache mod_proxy_html is not working

### ISSUE THREAD

**Issue by starrychloe** [heroku/heroku-buildpack-php#124]
The mod_proxy_html module is not working to translate URLs in the HTML when sending the contents back to the client's browser.

http://stackoverflow.com/questions/32751746/why-isnt-my-apache-reverse-proxy-working-to-translate-anchor-href-attributes-wh

Here is the `httpd_include.conf` file I currently have. It is working in my local development environment. 

```
DirectoryIndex index.php index.html index.htm
# For blog
LoadModule xml2enc_module libexec/mod_xml2enc.so
LoadModule proxy_html_module libexec/mod_proxy_html.so
LoadModule ssl_module libexec/mod_ssl.so
SSLProxyEngine on
ProxyRequests off
ProxyPass /guides https://shopwiz2.wordpress.com
ProxyPassReverse /guides https://shopwiz2.wordpress.com
ProxyHTMLEnable On
ProxyHTMLURLMap https://shopwiz2.wordpress.com /guides
<Location /guides>
  ProxyPassReverse /
  ProxyHTMLEnable On
  ProxyHTMLURLMap / /guides
  RequestHeader    unset  Accept-Encoding
  LogLevel proxy:debug
</Location>
```

Here is the HTML that appears in the browser, despite the `ProxyHTMLURLMap`:

    <a href="https://shopwiz2.wordpress.com/" rel="home">ShopWiz</a>

**Comment by dzuelke** [comment]
Since b71abaa34e36f25c33c359c5296fdd83634353d2
