### ISSUE TITLE
ext-phalcon * is missing

### ISSUE THREAD

**Issue by rochapablo** [heroku/heroku-buildpack-php#129]
I'm trying to add the **phalcon/incubator** and **phalcon/devtools** to my project.

But when I deployed to Heroku I got this error:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested PHP extension ext-phalcon * is missing from your system.
  Problem 2
    - Installation request for phalcon/devtools v2.0.8 -> satisfiable by phalcon/devtools[v2.0.8].
    - phalcon/devtools v2.0.8 requires ext-phalcon ~2.0 -> the requested PHP extension phalcon is missing from your system.
  Problem 3
    - Installation request for phalcon/incubator v2.0.8 -> satisfiable by phalcon/incubator[v2.0.8].
    - phalcon/incubator v2.0.8 requires ext-phalcon >=2.0.4 -> the requested PHP extension phalcon is missing from your system.
```

Using this configuration:

```
{
    "require": {
        "php": ">=5.5",
	"ext-phalcon": "*",
	"phalcon/incubator": ">=2.0.8",
	"phalcon/devtools": ">=2.0.8",
	"phpmailer/phpmailer": ">=5.2"
    },
    "require-dev": {
        "phpunit/phpunit": ">=4.7"
    }
}
```

But when I remove those paths, I got:

```
Build complete.
Don't forget to run 'make test'.
Installing shared extensions:     /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20131226/
Installing header files:          /app/.heroku/php/include/php/
Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation
important extension phalcon into php.ini
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing... done, 169.2MB
-----> Launching... done, v26
       https://buxfer.herokuapp.com/ deployed to Heroku
```

I was thinking that maybe the error occurs because the Phalcon extension is the last thing executed or installed, so when the composer runs i don't have the extension.

My question is, am I doing it right? If so how to install those dependencies without the error?

**Comment by sdrib** [comment]
I managed to install it using this article:
http://www.sitepoint.com/install-custom-php-extensions-heroku/

There is a related issue from a while ago:
https://github.com/heroku/heroku-buildpack-php/issues/62

**Comment by dzuelke** [comment]
It's been forever, but it's now finally ready for rollout next week. Thanks for your patience!

**Comment by rochapablo** [comment]
Nice! thanks

**Comment by dzuelke** [comment]
Now available: https://devcenter.heroku.com/changelog-items/794

**Comment by rochapablo** [comment]
Well done! Build success.

Before today, I was using another build pack, so I go back to this one and I got this error:

```
app[web.1]: 2016/01/08 09:54:21 [error] 101#0: *11 open() "/app/public/dashboard/index" failed (2: No such file or directo
ry)..."
```

Could this have something with the heroku-buildpack-php in specific?

**Comment by dzuelke** [comment]
Yeah could be (looks like Nginx; do you need rewrites?), but that's unrelated to this change. If you keep running into that, open a ticket at help.heroku.com and we'll take a look, @rochapablo

**Comment by rochapablo** [comment]
Yes I need rewrites. Oh sure no problem. I'm just using the other buildpack until I'm finish the project and after that I'll try again, for sure!

Thank you for your time.

**Comment by dzuelke** [comment]
See https://devcenter.heroku.com/articles/custom-php-settings#nginx for instructions for Nginx config @rochapablo.

**Comment by rochapablo** [comment]
Oh that make sense, lol I'll try this tonight.

Thank you again.
