### ISSUE TITLE
curl SFTP support

### ISSUE THREAD

**Issue by auro1** [heroku/heroku-buildpack-php#130]
Hi

The version of curl in the buildpack does not support sftp. I would really like it to.

**Comment by dzuelke** [comment]
Unfortunately, the Ubuntu system `libcurl` used by the Heroku Cedar-14 stack does not support SFTP, so we can't add it without building a custom `libcurl`, which is not an option for maintenance and security reasons.

**Comment by auro1** [comment]
Could this be pushed to Cedar-14 stack development?

**Comment by dzuelke** [comment]
Unlikely, @auro1. I will check, but I think with the exception of postgres and libpq, we only use official packages from Canonical.

**Comment by nelsounet** [comment]
Somebody can tell me how to do with buildpacks to add 'SFTP' support to curl (called from PHP) ? 
Heroku told me about https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt .

I only succeeded to add in in my app as the 1st buildpack but don't know what to do more...

**Comment by nelsounet** [comment]
Somebody can tell me how to do with buildpacks to add 'SFTP' support to curl (called from PHP) ? 
Heroku told me about https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt .

I only succeeded to add in in my app as the 1st buildpack but don't know what to do more...

**Comment by nelsounet** [comment]
Somebody can tell me how to do with buildpacks to add 'SFTP' support to curl (called from PHP) ? 
Heroku told me about https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt .

I only succeeded to add in in my app as the 1st buildpack but don't know what to do more...
