### ISSUE TITLE
ldap module is not enable on php

### ISSUE THREAD

**Issue by upendraq** [heroku/heroku-buildpack-php#131]
We need to enable a ldap module in php can you please help us.

**Comment by dzuelke** [comment]
Working on it. Needs a new build infra based on Docker, but getting closer. Thanks for your patience!

**Comment by upendraq** [comment]
Thank you !!

**Comment by dzuelke** [comment]
LDAP, with SASL support, is now available: https://devcenter.heroku.com/changelog-items/842 :)
