### ISSUE TITLE
pdo_pgsql with HHVM

### ISSUE THREAD

**Issue by iangcarroll** [heroku/heroku-buildpack-php#135]
I found [this StackOverflow comment](http://stackoverflow.com/questions/28841853/heroku-hhvm-pgsql) from March 2015 which said `pdo_pgsql` would be out with HHVM 3.6.0 - is it going to be released soon? When I try to require `ext-pgsql`, it errors out:

```
remote:        >     - Installation request for hhvm >=3.5.0 -> satisfiable by hhvm[3.5.1].
remote:        >     - Installation request for ext-pgsql * -> satisfiable by php[5.5.30, 5.6.16, 7.0.0, 7.0.1].
```

**Comment by dzuelke** [comment]
We're working on new HHVM versions, and with `ext-pgsql`. It'll be just a few weeks before they're out. Thanks for your patience!
