### ISSUE TITLE
Add apcu with bc support to php 7.0

### ISSUE THREAD

**Issue by robinvdvleuten** [heroku/heroku-buildpack-php#137]
Is it possible to add bc support to the apcu extension in php 7.0?

**Comment by abgit** [comment]
btw, seems to be released a new `apcu` version [5.1.3](http://pecl.php.net/package/APCu/5.1.3), 2 days ago.

**Comment by dzuelke** [comment]
Will do @robinvdvleuten give me ~a week (it was already on my todo :))

Yup I'm aware @abgit!

**Comment by holtkamp** [comment]
Any update on this? Seems to be last argument to not switch to PHP 7 :smile:

**Comment by dzuelke** [comment]
Working on it, @holtkamp. It's a bit complicated with configs etc - `ext-apcu` on 5.x provides `ext-apc`, but for PHP 7, it'll be a separate extension (so you need to require `ext-apc` as well), and I need to ensure proper loading order, the right info in the manifests so Composer can resolve it for installs etc. Thanks for your patience :)

**Comment by holtkamp** [comment]
thanks for the update, no worries, no hurries, was just curious ;)

**Comment by dzuelke** [comment]
(the alternative may be to forcefully install the backwards compatibility mode for PHP 7 as well, but that's probably not the best long-term choice, because people will keep relying on `apc_*` being there when they require `ext-apcu`)

**Comment by robinvdvleuten** [comment]
Awesome @dzuelke, thanks for the hard work!
