### ISSUE TITLE
The lock file freshness should use the content-hash when available

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#141]
Since mid 2015, Composer has a smarter hashing system for the lock file freshness, avoiding to mark the lock file as outdated when changing the package description for instance (as it does not impact the dependency resolution). but the buildpack still complains about an outdated lock file

**Comment by dzuelke** [comment]
Yeah I know, it's on my list. I just don't want to copy/paste the Composer logic for that. The `composer validate` command should have a `--lock` switch or something to only check freshness. I'd then use that in the buildpack. Seems cleaner, no?

**Comment by dzuelke** [comment]
(I'll do that PR for Composer when I have time but if you wanna beat me to it, by all means please do :D)

**Comment by stof** [comment]
This looks like a good idea. Please open an issue in the composer repo to request the feature, to allow anyone to pick it.

**Comment by dzuelke** [comment]
Actually it looks like `composer validate --no-check-all --no-publish --quiet` does exactly that.
