### ISSUE TITLE
New Relic extension required for add-on not properly installed when promoting an Application in Pipeline

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#145]
Hey guys, 

some feedback about the Pipelines feature. 

**Context**
We have 3 Heroku applications in an Heroku Pipeline:

- Development (no New Relic addon installed)
- Staging (no New Relic addon installed)
- Production (New Relic addon installed!)

**Problem**
It appears that when promoting a slug from staging to production, it is not detected that the New Relic extension should be installed. And therefore when looking at phpinfo() of the Production environment:
- NEW_RELIC_LICENSE_KEY is defined
- no new Relic Extension is installed

It seems [this script](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/util/newrelic.sh) should install New Relic automatically after detecting the presence of the ```NEW_RELIC_LICENSE_KEY``` variable. Apparently this script is not executed, or fails?

**Additional info**
As a test I provisioned the New Relic addon to:

- the Staging Application, which was 'promoted' from test. The New Relic addon extension seems not to install as well.
- the Test Application, which was 'git pushed' from my local machine. The New Relic addon extension seems not to install as well.

**Interesting**
- when running a *new* git push to the Test Application, New Relic extension was installed properly and data was received by New Relic.
- when promoting THAT Test version to Staging, New Relic extension is installed properly. 
- when promoting THAT Staging version to Production, New Relic extension is installed properly. 

So it seems to only fail when the New Relic addon is not installed on an Application and one promotes that version upstream.

**Comment by dzuelke** [comment]
The newrelic extension gets installed during a deploy, not on boot. This is currently by design, as downloading and installing it is potentially a time-consuming process, which would slow down dyno boots (and be executed for each dyno, which is also not ideal).

I've toyed with the idea before to simply install `newrelic` and `blackfire` unconditionally, and then dynamically enabling them on dyno boot.

In the meantime, you can just enable the free newrelic add-ons for dev and staging.

**Comment by holtkamp** [comment]
Aah, ok, that clarifies this situation. It might be worthwhile to mention this (example) in the documentation? Maybe it is already there, then I must have missed it...

Indeed, provisioning the add-ons on all applications prevents the problem and I guess 100% identical application environments would be a best practice as well :smile: 

Closing this issue.

**Comment by dzuelke** [comment]
I updated the https://devcenter.heroku.com/articles/php-support#extensions docs for these extensions to say "during a build".

I've noted dynamic on-boot enabling as a feature request. I think it would make sense to have this, so expect it to land eventually :)
