### ISSUE TITLE
Advice for Composer speed up

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#148]
Related to https://github.com/heroku/heroku-buildpack-php/issues/143, but better to keep it separated since this has nothing to do with [Prestissimo](https://github.com/hirak/prestissimo).

Unfortunately [CloudControl](www.cloudcontrol.com) will shut down their services by the end of this month. When following [their advice and migrating our applications running on Apache/PHP to Heroku](http://www.paasfinder.com/how-to-migrate-from-dotcloud-to-heroku/), I noticed an:
- increased build time (this includes some actions on a local machine, but to give an idea)
 - 4 minutes on CloudControl, of which around 1,5 minute is used by Composer to download dependencies
 - 8 minutes on Heroku, of which around 7 minutes is used by Composer to download dependencies
- increased image/slug size: 
 - 92.0MB on CloudControl (as mentioned during push), ```du -sh vendor```: 152M, ```du -sh /```: 1.4G
 - 131.2MB on Heroku (as mentioned during push), ```du -sh vendor```: 165M, ```du -sh /```: 1.9G

Note that the code is exactly the same and the content of the used ```.slugignore``` and CloudControl's equivalent ```.cctrlignore``` is identical. Only the PHP version differ, ```php-5.6.15``` vs ```php-5.6.18``` on Heroku.

**Allow / Enable profile information**
CloudControl allows users to influence the arguments handed over to Composer using a ```COMPOSER_INSTALL_ARGS``` environment variable. It might be useful to adopt this approach so one can use arguments like ```--verbose --profile``` to gather some more information about the build process.

**Article** 
These observations reminded me of an interesting [blog post](http://www.paasfinder.com/faster-instances-ssd-backed-storage-and-improved-build-process-performance/) by @pst, might be interesting for Heroku as well to read this and perhaps reach out to @pst for some tips and tricks they gathered the last years?

And just being curious, Heroku probably uses a cache for Composer like [Toran](https://toranproxy.com/) right?

**Comment by dzuelke** [comment]
Lower slug sizes are on my todo for the next weeks; I'll be able to shave off at least 50% in size.

Does it take eight minutes each time, or on first push only (when no cache exists yet)? That's pretty substantial - do you have complicated `post-install-cmd` steps?

We do not run a Toran proxy. Our instance types are similar to what CloudControl are describing.

Can you create a separate ticket for `COMPOSER_INSTALL_ARGS` please?

**Comment by holtkamp** [comment]
Thanks for the response. 

Yeah the build times are very stable around that 8 minutes. If you want I can keep track of them for a while?

**Comment by holtkamp** [comment]
@dzuelke interesting observation. I managed get our dependencies down to a set that is installable with ```PHP 7.0.3```, which halves the build time as reported by my machine to 4 minutes and 30 seconds. It seems the Composer dependencies are downloaded / processed way faster...

**Comment by dzuelke** [comment]
Yeah PHP 7 is faster, although it should not be resolving the dep tree with a lock file present, so performance wise, I am surprised the difference is that large.

**Comment by holtkamp** [comment]
yeah, that was my idea as well. No resolving should take place, only downloading, same surprise here ;)

**Comment by holtkamp** [comment]
slug size has been halved in size, @dzuelke want me to close this issue? :smile:

**Comment by holtkamp** [comment]
Another intermediate observation:

- since yesterday our deploy times are back to 4 minutes again, nice!
 - guess this is because composer now runs under PHP 7 (again?), 
- slug size around 65M, nice!
 - ```du -sh vendor```: 165M
 - ```du -sh /```: 303M (was 1.9G) nice!

Only the difference in the ```vendor``` size might be something for extra research. But not a biggy, so maybe this issue can be closed?

**Comment by dzuelke** [comment]
There have been no significant changes; Composer has been running with PHP 7 for a while if your app allows PHP 7. Could be network I/O, depending on how many packages you have? Maybe you also ran into GitHub rate limits before and it fell back to Git clones? GitHub removed limits a short while ago.

Slug size should be up slightly since yesterday, but only by 100 or 200 kB now that `ext-imap` is included.

**Comment by holtkamp** [comment]
mm, ok, well, no changes here as well. Most of the packages (118 out of 133 in total) are loaded "from cache" according to Composer. Will keep monitoring our buildtimes, but I think this issue can be closed, will re-open when applicable.

**Comment by holtkamp** [comment]
UPDATE

We had some hooks in place [Command Events](https://getcomposer.org/doc/articles/scripts.md#command-events) and [Package Events](https://getcomposer.org/doc/articles/scripts.md#package-events) which did nothing else than output some debug information. 

Removing these hooks **drastically** reduced the installation time of (cached) packages. 

Problem solved.
