### ISSUE TITLE
New Relic extension won't work on HHVM

### ISSUE THREAD

**Issue by maxehmookau** [heroku/heroku-buildpack-php#149]
I've lost nearly a day on this, and I think it's probably my fault but it doesn't appear to be possible to install the built-in NR extension when using HHVM on the php buildpack.

```
remote: -----> Checking for additional extensions to install...
remote:        NOTICE: Using custom New Relic config 'newrelic.ini'
remote: /app/tmp/buildpacks/php/bin/util/newrelic.sh: line 53: cd: /tmp/build_251b7a28063dd325f9ef5b715f2cbd8a/.heroku/php/etc/php/conf.d: No such file or directory
```

After tearing my hair out, I remembered, **it's probably HHVM's fault.**

I'm assuming this file doesn't exist when using HHVM as the PHP runtime. As HHVM isn't officially supported by Heroku at this point (which is fine), might I suggest a more helpful error when attempting to install the NR extension on a HHVM app?

```
remote:  !     Push rejected, failed to install New Relic extension. Use PHP instead of HHVM.
```

Happy to submit a PR with changes to https://github.com/heroku/heroku-buildpack-php/blob/master/bin/util/newrelic.sh if someone can confirm this is the issue?

**Comment by djtarazona** [comment]
Do my understanding, New Relic does not support HHVM: https://discuss.newrelic.com/t/php-agent-and-hhvm/2805/62

**Comment by maxehmookau** [comment]
@djtarazona Right you are! Ok, I'll submit a PR to point this out to people like me.

**Comment by dzuelke** [comment]
They do not support HHVM, and this is documented at https://devcenter.heroku.com/articles/php-support#extensions-hhvm

But it looks like your issue is that when you have `NEW_RELIC_CONFIG_FILE` set, the build crashes. That should not happen. Will fix.

**Comment by maxehmookau** [comment]
Excellent. Thanks @dzuelke :)
