### ISSUE TITLE
Make Application ID and/or name available to environment

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#152]
[This section of the API documentation](https://devcenter.heroku.com/articles/platform-api-reference#dyno-restart) indicates that to be able to restart a Dyno, one needs to 'know' both:

- $APP_ID_OR_NAME
- $DYNO_ID_OR_NAME

When restarting all Dynos, the ```$APP_ID_OR_NAME``` is required.

Suppose I want to have an Application initiate a restart for whatever reason / to see how our application deals with that / clear up memory from APCu caches that have become 'too much' etc. Then it would nice that an environment is aware of these variables.

For a PHP application, phpinfo() provides an overview of the available environment variables. That overview does contain a variable ```DYNO```, but nothing related to the Application ID or name...  Might it be an idea to add it so the Application is a bit more self-aware, or am I missing something where I can find it?

**Comment by dzuelke** [comment]
The functionality you're looking for is currently available behind a labs flag: https://devcenter.heroku.com/articles/dyno-metadata

This is not a PHP buildpack related ticket, so I'll close it. Feel free to submit a general platform feature request through https://help.heroku.com.

**Comment by holtkamp** [comment]
ok, thanks for the pointer, and sorry for the double work..
