### ISSUE TITLE
New Relic agent 6.0.0.155 with PHP 7

### ISSUE THREAD

**Issue by djtarazona** [heroku/heroku-buildpack-php#153]
New Relic has finally released PHP 7 support!

https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-600155

@dzuelke can we get this added as an available 3rd-party extension? Please and thank you!

**Comment by dzuelke** [comment]
Yes, of course, will release soon!

**Comment by djtarazona** [comment]
@dzuelke Awesome!

Damn that has to be a record response time...

<img width="389" alt="screen shot 2016-03-07 at 20 34 32" src="https://cloud.githubusercontent.com/assets/337986/13589203/0b800c34-e4a4-11e5-82cf-bca6483f6e7c.png">

Thanks! :)

**Comment by jonahgeorge** [comment]
Will it take some time or should the extension already be available?
Just tried a build and got this (Add-on is present, `NEW_RELIC_LICENSE_KEY` is set, PHP v7.0.4):
```
-----> Checking for additional extensions to install...
 !     WARNING: New Relic detected, but no suitable extension available
Using release configuration from last framework (PHP).
```

**Comment by dzuelke** [comment]
Extension is no longer available due to a regression in the extension that crashes at least Laravel apps: https://devcenter.heroku.com/changelog-items/843

**Comment by jonahgeorge** [comment]
Ok, thanks. Hadn't seen that update.

**Comment by dzuelke** [comment]
It went out just a few minutes ago, @jonahgeorge, so it's not published yet :)

**Comment by djtarazona** [comment]
@dzuelke version 6.1.0.157 was released a few days ago. They've fixed the issue with Laravel 5.2 apps and a potential segfault. Based on feedback from the forums, no one has reported any issues with this version.  Could we give it a shot? :)

**Comment by dzuelke** [comment]
It's already prepared and built, @djtarazona; we just don't roll out changes on weekends :)

**Comment by djtarazona** [comment]
@dzuelke I saw on Twitter that the updated PHP extensions, including New Relic 6.1.0.157 with PHP 7 support, was released. However I'm still receiving the following when pushing a new commit / deploy to Heroku.

`WARNING: New Relic detected, but no suitable extension available`

Is there a delay or cache or something? Thanks! :)

**Comment by dzuelke** [comment]
https://devcenter.heroku.com/changelog-items/853

**Comment by dzuelke** [comment]
There should not be a delay @djtarazona. Can you please file a ticket at help.heroku.com for your app and grant full access?

**Comment by dzuelke** [comment]
Or if you `heroku run bash`, then `cd .heroku/php`, and `composer require "heroku-sys/ext-newrelic:*"`, do you get a `PREG_BACKTRACK_LIMIT_ERROR` exception, @djtarazona?

**Comment by djtarazona** [comment]
@dzuelke No I get the following when I run `composer require "heroku-sys/ext-newrelic:*"`:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing heroku-sys/ext-newrelic (5.1.1.130)
  - Installing heroku-sys/ext-newrelic (6.1.0.157)

Installation failed, reverting ./composer.json to its original content.

                                                                                        
  [ErrorException]                                                                      
  file_put_contents(./composer.json): failed to open stream: No such file or directory
```

**Comment by djtarazona** [comment]
Interesting... when I put `"ext-newrelic": "*"` in my `composer.json` (and run `composer update` to update the lock file), it seems like the New Relic extension installs successfully:

```
remote: -----> Installing platform packages...
remote:        - php (7.0.4)
remote:        - ext-exif (bundled with php)
remote:        - ext-gd (bundled with php)
remote:        - ext-mbstring (bundled with php)
remote:        - ext-newrelic (6.1.0.157)
...
```

But when I remove it and rely on auto-detection using the `NEW_RELIC_LICENSE_KEY ` env var, it fails again with `WARNING: New Relic detected, but no suitable extension available`.

For now, I'll force / fix it by requiring `"ext-newrelic": "*"` in my `composer.json`. Do you still want me to open a ticket?

**Comment by dzuelke** [comment]
Yes please remove that explicit requirement again and open a ticket, @djtarazona, so I can reproduce and get to the bottom of this! Will do it right away, so you won't be without `ext-newrelic` for long (ref this convo in the ticket and ask for immediate escalation to the PHP team).

**Comment by djtarazona** [comment]
Thanks @dzuelke! Ticket #347937.

**Comment by holtkamp** [comment]
@dzuelke this https://github.com/heroku/heroku-buildpack-php/issues/153#issuecomment-199807615 mean this issue needs/should be reopened?

**Comment by dzuelke** [comment]
No @holtkamp, New Relic is available again for PHP 7 (https://devcenter.heroku.com/changelog-items/853)

**Comment by holtkamp** [comment]
ok, great. Just add the add-on and indeed, it now works out of the box :smile:

**Comment by tdmalone** [comment]
Is this still a known issue? In my build log I'm getting:

```
-----> Checking for additional extensions to install...
 !     WARNING: New Relic detected, but no suitable extension available
```

I tried adding `"ext-newrelic": "*"` to my `composer.json` but receive the same error. I don't fully understand the architecture of buildpacks, but from [this source](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/util/newrelic.sh) it looks like it tries to install either way, but I'm not entirely sure if I can access the install.log it's piping to.

**Comment by dzuelke** [comment]
You're running PHP 7.2, @tdmalone, but there is no New Relic extension yet for that version, so it skips installation.

**Comment by dzuelke** [comment]
(and if you add an explicit requirement to `composer.json`, you must of course re-generate `composer.lock` for the requirement to take effect as described in great detail at https://devcenter.heroku.com/articles/php-support#using-optional-extensions; there is also a big warning on build that tells you the lock file is outdated)
