### ISSUE TITLE
PHPRedis Support for PHP7

### ISSUE THREAD

**Issue by mikelohmann** [heroku/heroku-buildpack-php#162]
It would be really great to have the phpredis extension available for PHP7, too.
Are there some general issues like dependent library versions or known issues?

**Comment by dzuelke** [comment]
There is no `ext-redis` yet for PHP 7; see https://pecl.php.net/package/redis.

Once there is a functioning stable release we'll make it available (it's a common request).

You can follow, lobby, and assist development progress at https://github.com/phpredis/phpredis
