### ISSUE TITLE
ext-libsodium inclusion?

### ISSUE THREAD

**Issue by WillSkates** [heroku/heroku-buildpack-php#163]
Is there any chance of including [ext-libsodium](https://pecl.php.net/package/libsodium) and [libsodium](https://github.com/jedisct1/libsodium/tree/1.0.10) for PHP 5.5._, 5.6._ and 7.*?

**Comment by stof** [comment]
@WillSkates I just created https://github.com/Incenteev/heroku-php-exts to provide additional extensions not maintained by the Heroku team (@dzuelke designed an extensible system to make this possible, and then pushed me to use it for months).
You may want to contribute there to provide support for it (given that I'm not suing ext-libsodium myself, I won't work on adding it myself any time soon, but I will gladly accept contributions)

**Comment by dzuelke** [comment]
This has been available since 01f9e2cd
