### ISSUE TITLE
Describe support for post compilation scripts

### ISSUE THREAD

**Issue by aik099** [heroku/heroku-buildpack-php#165]
By looking at `heroku-buildpack-php/bin/compile` file I've found, very interesting line:

```bash
composer run-script --no-dev --no-interaction compile 2>&1 | indent
```

It runs the `compile` script defined within `composer.json` file. The use case for it can be running a DB migrations upon each deploy.

It would be great if it could be documented.

**Comment by aik099** [comment]
I've just realized that the `compile` script isn't right way to run db migrations considering how Heroku works and fact that build can be rolled back. Still fact of existence of such feature needs to be documented.

**Comment by dzuelke** [comment]
It is documented: https://devcenter.heroku.com/articles/php-support#custom-compile-step

**Comment by aik099** [comment]
Ups. Had to search harder I guess. Sorry.
