### ISSUE TITLE
How to run database migrations

### ISSUE THREAD

**Issue by aik099** [heroku/heroku-buildpack-php#166]
What is proper way to run DB migrations after deployment was made, but prior to dyno with new App version replaces dyno with old App version?

What about build rollback? How to perform migration rollback for all builds between one rollback happens to and last deployed?

**Comment by djtarazona** [comment]
This has to be done manually by starting a [One-Off Dyno](https://devcenter.heroku.com/articles/one-off-dynos) and running your migration command.

**Comment by dzuelke** [comment]
You can use https://devcenter.heroku.com/articles/release-phase to do that.

**Comment by aik099** [comment]
Thanks.
