### ISSUE TITLE
ext-memcached/2.2.0 for php70

### ISSUE THREAD

**Issue by larsschenk** [heroku/heroku-buildpack-php#168]
I get "Your requirements could not be resolved to an installable set of packages." because of 

composer.json/composer.lock dev-71658fc7fefe9f4000d99cf9d7e62c59 requires ext-memcached * -> satisfiable by ext-memcached[2.2.0].        
ext-memcached 2.2.0 requires php 5.5.* -> satisfiable by php[5.5.35, 5.5.36, 5.5.37].        
ext-memcached 2.2.0 requires php 5.6.* -> satisfiable by php[5.6.21, 5.6.22, 5.6.23].        

Does it mean that ext-memcached is (still) not available for php7 ?

**Comment by larsschenk** [comment]
Oh, I think I see where the blocker is: https://github.com/php-memcached-dev/php-memcached/issues/213

**Comment by dzuelke** [comment]
Correct
