### ISSUE TITLE
Enable mssql driver support

### ISSUE THREAD

**Issue by chillyistkult** [heroku/heroku-buildpack-php#175]
Is it possible to add mssql driver support to the list of custom extensions that can be enabled? Or is there a way to manually add extensions to the buildpack?

**Comment by dzuelke** [comment]
We have no plans to support that. `mssql` is no longer available in PHP 7, so there is only ODBC left as an option, and that's a bit of a nightmare to set up on Linux.

If you want to try building the extension yourself, you don't need to fork the buildpack. You can maintain an S3 bucket or similar with your own extension builds and add those. See https://github.com/Incenteev/heroku-php-exts for an example and https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/README.md for some docs.

**Comment by chillyistkult** [comment]
Thank you very much for the fast response. I will move to AWS as they support this out of the box, don't want to encounter  devops nightmare on simple things.
