### ISSUE TITLE
Latest Phalcon Extension

### ISSUE THREAD

**Issue by dev6** [heroku/heroku-buildpack-php#176]
The change log of this build pack says that the Phalcon extension was last updated in Feb this year to versioin 2.0.10. Is it discontinued now? I see the latest Phalcon version is 3.0.1

**Comment by dzuelke** [comment]
Soon. ee06ad770e12e37199cdf27991cfddf1ebc33115

**Comment by dzuelke** [comment]
https://devcenter.heroku.com/changelog-items/961
