### ISSUE TITLE
heroku-buildpack-php broken on macOS Sierra (10.12)

### ISSUE THREAD

**Issue by jussikinnula** [heroku/heroku-buildpack-php#179]
**Prequisities:**

- OSX updated to macOS Sierra (10.12)
- Xcode updated to latest
- Homebrew packages updated to latest
- Note that "bedrock-on-heroku" has it's own set of prequisities, like installing Homebrew packages for PHP, MySQL, etc

**Steps to reproduce:**

1. Clone https://github.com/frc/bedrock-on-heroku (WordPress "bedrock" installation, with deployment setup for Heroku)
2. Switch to the cloned directory
3. Install composer packages
4. Start Heroku Local

**Expected result:**

Heroku Local starts without any issues

**Actual result:**

Heroku Local fails to start, because heroku-buildpack-php (more specifically `vendor/bin/heroku-php-nginx` -script) is broken.

See further details (e.g. terminal output) from:
https://gist.github.com/jussikinnula/d2f93b64cc2feed52a614d3d5b6a47c3

**Comment by JanneAalto** [comment]
This only applies when composer is installed from homebrew

**Comment by JanneAalto** [comment]
fix https://github.com/heroku/heroku-buildpack-php/pull/180
