### ISSUE TITLE
failed to create symbolic link ‘/app/.heroku/php/php’

### ISSUE THREAD

**Issue by luemic** [heroku/heroku-buildpack-php#181]
Hi guys,

when using the buildpack I got the following error:

    ln: failed to create symbolic link ‘/app/.heroku/php/php’: File exists

What's the cause for it and what can I do?

Kind regards

Michael

**Comment by dzuelke** [comment]
Uh... when and where are you getting that error?

**Comment by luemic** [comment]
Hi,

that were the last steps before the error occurs:

    -----> Preparing runtime environment...
    remote: -----> Checking for additional extensions to install...
    remote: Using release configuration from last framework (PHP).
    remote: -----> PHP app detected
    remote: ln: failed to create symbolic link ‘/app/.heroku/php/php’: File exists
    remote:  !     Push rejected, failed to compile PHP app.

Hope that helps. 

Kind regards

Michael

**Comment by dzuelke** [comment]
Could you open a support ticket please so we can investigate for you? Thanks!

**Comment by jkvora** [comment]
Hello ,
          I am also facing the same issue.Can you let me know what i am doing wrong.
Thanks,
Jalak

**Comment by dzuelke** [comment]
Please open a ticket for the app at https://help.heroku.com and remember to grant code access @jkvora

**Comment by jkvora** [comment]
Thanks @dzuelke  .The issue was  occuring because  i had added  buildpack of php multiple times .Once i removed all of them and added only once it worked like a charm.
