### ISSUE TITLE
with-http_ssl_module

### ISSUE THREAD

**Issue by urshofer** [heroku/heroku-buildpack-php#182]
It would be nice if nginx would include with-http_ssl_module. Like this, it would be possible to use proxy_pass also to https sources.

**Comment by dzuelke** [comment]
Thanks, I've put that on the roadmap!

**Comment by incrize** [comment]
bump, @dzuelke  what your thoughts about this one? Any news?

**Comment by beNjiox** [comment]
Hey @dzuelke Thanks for maintaining this.

I could really use this but understand you may be busy with other stuff.
I you could point me on where the changes needs to be made in order to get the module I'm willing to make a PR ASAP.
