### ISSUE TITLE
APCu not working

### ISSUE THREAD

**Issue by Nekress** [heroku/heroku-buildpack-php#189]
Hey, I read that APCu is installed by default, but it seems that none of the functions (apc_add; apc_store; apc_exists) are working. Do I need to enable something somewhere in order for it to work?

**Comment by dzuelke** [comment]
It is not enabled by default; see https://devcenter.heroku.com/articles/php-support#extensions

If your application depends on `ext-apcu`, then it should declare that dependency in `composer.json` so Heroku can enable it. Please follow the documentation at https://devcenter.heroku.com/articles/php-support#using-optional-extensions
