### ISSUE TITLE
Unable to load apc and soap libraries

### ISSUE THREAD

**Issue by imuino** [heroku/heroku-buildpack-php#19]
Hi,
When the compilation get to php, it throws the following errors.

PHP Warning:  PHP Startup: Unable to load dynamic library '/app/php/ext/apc.so' - /app/php/ext/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0

PHP Warning:  PHP Startup: Unable to load dynamic library '/app/php/ext/soap.so' - /app/php/ext/soap.so: cannot open shared object file: No such file or directory in Unknown on line 0

I read on another issue that apc should be compiling with the latest version of this repo.

Any idea what could be the issue here?

Thanks in advance.

**Comment by rajeevdubey004** [comment]
not working and still getting FATAL ERROR "SoapClient class is not found"
Below is the attached log
2015-08-12T06:59:12.228052+00:00 app[web.1]: [12-Aug-2015 06:59:12 UTC] PHP Fata
l error:  Class 'SoapClient' not found in /app/web/soapclient/SforcePartnerClien
t.php on line 44

**Comment by dzuelke** [comment]
Please read the documentation at https://devcenter.heroku.com/articles/php-support#using-optional-extensions carefully and follow all steps.
