### ISSUE TITLE
HEROKU_PHP_INSTALL_DEV variable

### ISSUE THREAD

**Issue by Laruxo** [heroku/heroku-buildpack-php#194]
In the compilation script I found variable HEROKU_PHP_INSTALL_DEV that in theory should allow me to install composer dev dependencies, but it doesn't seem to work (I know that this is not the best practice, but if there is a variable it should work).
I tried setting it to "--dev" and some other values, but it seems that it is not included at all.
Could you clarify if/how it works?

**Comment by dzuelke** [comment]
This is, intentionally, for internal buildpack use only (by the `bin/test-compile` script, which sets it, so that builds for Heroku CI have dev dependencies installed).

**Comment by FelixMalfait** [comment]
Hello!
What's the recommended way to install dev dependencies in the dev environment then?
I need to install `fzaninotto/faker` in order to seed the database.
Thanks!

**Comment by dzuelke** [comment]
If you need it to seed an application's DB, then it's not a dev dependency ;)

The alternative is to generate the data once, dump it, and import that dump to bootstrap your DB.
