### ISSUE TITLE
Symfony deployment not pointing to the web folder 

### ISSUE THREAD

**Issue by shairyar** [heroku/heroku-buildpack-php#196]
I am trying to deploy the symfony app on heroku and I am able to update the schema and all perfectly fine however when i try to access the site I get

> Forbidden You don't have permission to access / on this server.

So using the command` heroku logs --num 10` i can see the error

> Cannot serve directory /app/web/: No matching DirectoryIndex (index.php,index.html,index.htm) found, and server-generated directory index forbidden by Options directive

In Symfony the directory that is public is called `web` As you can see heroku is trying to access /app/web/ rather than just web, because of this even my assets are being access via app/web/css which is ofcourse wrong.

So how can i get rid of this `app`? I do not understand why Heroku is even pointing at that.

The Procfile seems to be point to web so where is this app coming from?

`web: vendor/bin/heroku-php-apache2 web/`

Any help will be really appreciated as I am pretty much lost here.

**Comment by dzuelke** [comment]
`/app/web/` is the absolute location on the file system. This is not the problem. Your `Procfile` is also correct. The issue you are having is described right there in your error message:

> Cannot serve directory /app/web/: No matching DirectoryIndex (index.php,index.html,index.htm) found, and server-generated directory index forbidden by Options directive

So you don't have an `index.php` or similar, as Symfony uses `app.php`, and you have no rewrites in place to send traffic to `app.php`. Is your `.htaccess` maybe not in version control?
