### ISSUE TITLE
[Suggestion] Use the heroku app name as default name for newrelic

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#199]
When ``NEW_RELIC_APP_NAME`` is not set (and it is not set by default), it would be useful to try using ``HEROKU_APP_NAME`` before the fallback to ``PHP Application on Heroku``

**Comment by dzuelke** [comment]
Good idea, thanks! :) Where's the PR? ;)

**Comment by stof** [comment]
I wanted to have your feedback first

**Comment by dzuelke** [comment]
Go for it ;)

**Comment by stof** [comment]
here you go

**Comment by josegonzalez** [comment]
This can be closed :)

**Comment by dzuelke** [comment]
Yes it can :)

**Comment by dzuelke** [comment]
Thanks @stof!
