### ISSUE TITLE
Nginx 1.9.5 or higher

### ISSUE THREAD

**Issue by jessedobbelaere** [heroku/heroku-buildpack-php#201]
Currently the supported Nginx version in this buildpack is 1.8.1. 

Is there a possibility that we can upgrade to Nginx 1.9.5 or higher? The latest mainline version of Nginx is 1.11.7. 

The reason why i'm asking is that I want to have HTTP/2 support which is only available in Nginx >1.9.5

**Comment by dzuelke** [comment]
It's on the list, but for Nginx, we currently provide the latest stable versions.

You do have the option of supplying your own builds, see `support/build/README.md`.

Note however that Heroku currently does not support HTTP/2 on the routing layer.

**Comment by jessedobbelaere** [comment]
Ok, thanks for the reply! Latest stable version is nginx-1.10.2 so would be great switching to that version. 

* I use both Heroku and [Dokku](http://dokku.viewdocs.io/dokku/) which uses heroku buildpacks to spin up docker containers, so http/2 support would be nice as the reverse nginx proxy in dokku supports http/2 but not the underlying app with nginx server 1.8.1.
