### ISSUE TITLE
Composer upgrade?

### ISSUE THREAD

**Issue by asm89** [heroku/heroku-buildpack-php#202]
When trying to push a commit containing a `composer.lock` file generated by the latest stable version of composer (`1.3.0`) the file gets rejected. When I install an older version (`1.2.x`), run `composer update`, commit and push again everything is fine.

There is a one field difference between the old and new `.lock` file. I assume that `1.3.x` is happy reading `1.2.x` lock files, but not the other way around. The lock file change is mentioned in the changelog of the 1.3.0 release:

> Removed hash from composer.lock, only content-hash is now used which should reduce conflicts
> https://github.com/composer/composer/releases/tag/1.3.0.

**Comment by dzuelke** [comment]
Works fine for me. Do you maybe have an old `composer.phar` in your Git repo? Heroku will use that for installation if present.

**Comment by asm89** [comment]
A committed `.phar`? No.

I'm unblocked for now. If I find time I'll see if I can reproduce it for you (if at all).

**Comment by dzuelke** [comment]
Yeah committed.

I just generated a new lock with 1.3 and pushed. Worked fine.

Where does it get rejected? Early on by the buildpack, or during install by composer itself?

Are you on an old buildpack revision or on a branch? See #183

**Comment by asm89** [comment]
Ah, I thought I was on `v117` but apparently it was `v110`. :/ Sorry for wasting your time, but thank you for the quick replies.

**Comment by dzuelke** [comment]
No worries!
