### ISSUE TITLE
Issue with phpredis extension on v3.1

### ISSUE THREAD

**Issue by eddturtle** [heroku/heroku-buildpack-php#205]
With the new release of phpredis (v3.1) we're getting this error:

    session_regenerate_id(): Failed to create(read) session ID: redis (path: ...)

Which can be fixed by down-grading back to v3.0. We've changed our composer from `"ext-redis": "*"` to `"ext-redis": "3.0"` which has sorted this problem. I understand there's a v3.1.1 in the works which might fix our issues but I believe it's in testing at the moment.

**Comment by boboldehampsink** [comment]
Same here, lots of issues with 3.1.0

**Comment by dzuelke** [comment]
Thanks for the info; I have removed 3.1.0 from the repo.

@boboldehampsink does 3.1.1 fix the issues for you as well?

**Comment by boboldehampsink** [comment]
I have tried 3.1.1RC1, that fixes the issues indeed.

**Comment by dzuelke** [comment]
Excellent. Feel free to root for a quick tag and release of 3.1.1 in phpredis/phpredis#1062 ;)

**Comment by boboldehampsink** [comment]
Done

**Comment by eddturtle** [comment]
Thanks :)
