### ISSUE TITLE
Regression in v118? "Push rejected, failed to compile PHP app"

### ISSUE THREAD

**Issue by danielstjules** [heroku/heroku-buildpack-php#206]
Since v118  was released, all app deploys have been failing with:

```
-----> Deleting 10 files matching .slugignore patterns.
-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
       - hhvm (3.5.1)
       - apache (2.4.20)
       - nginx (1.8.1)
-----> Installing dependencies...
 !     Push rejected, failed to compile PHP app.
 !     Push failed
```

Temp solution has been to require v117 rather than running on latest:
https://github.com/heroku/heroku-buildpack-php.git#v117

Any idea what's up?

Thanks!

**Comment by dzuelke** [comment]
Could you please open a ticket at https://help.heroku.com/tickets/new, or share a reduced code sample I can use to reproduce this?

**Comment by dzuelke** [comment]
Nevermind, got it; seems HHVM related. Investigating.

**Comment by dzuelke** [comment]
Fixed by reverting Composer. See https://github.com/composer/composer/issues/6092 for underlying issue.

Thanks for the report, and apologies for the inconvenience!

**Comment by danielstjules** [comment]
Thanks! :)
