### ISSUE TITLE
Default to reading all logs via `logs/*.log`

### ISSUE THREAD

**Issue by josegonzalez** [heroku/heroku-buildpack-php#208]
A common framework pattern is to use the `logs/` directory for logging in applications. I suggest that if `/app/logs` exists and no `-l` argument is specified, we default to the `logs/*.log` pattern for reading logs. This will make the default file-logging experience much nicer for developers, as they will not need to change loggers to `php://stderr`, nor will they need to change their Procfile.

**Comment by dzuelke** [comment]
That's not useful, because the glob pattern is a shell construct that expands to a list of matched files on execution, so it cannot pick up files that are added at runtime.

**Comment by dzuelke** [comment]
(and besides, writing log files to local disk is becoming quite the anti-pattern these days, with Docker et cetera)

**Comment by josegonzalez** [comment]
Interesting, hadn't thought of the runtime issue. Good call.

**Comment by dzuelke** [comment]
For those wondering: you can `heroku-php-apache2 -l log/debug.log`, then it tails that; if `log/debug.log` doesn't exist, it'll be `touch`ed.

You can also `heroku-php-apache2 -l log/*.log`, but that's a shell pattern, so it will expand to a list of files that already exist in `log/` - `tail` cannot magically also follow future created files in a directory.

That means that for this to be useful in the sense that it picks up every log your app writes, you have to have a dummy empty log file each in the `log/` directory, which is super cumbersome, and you're better off just changing your Monolog config for production to dump errors to `php://stderr`, which in today's world of Docker, PaaSes etc is better anyway.
