### ISSUE TITLE
memcached support for php7

### ISSUE THREAD

**Issue by vlahanas** [heroku/heroku-buildpack-php#210]
Hello all,
I want to enable memcached session management in a symfony application that is supposed to maintain a persistent session storage while running on multiple dynos. However, i cannot deploy with ext-memcached as it is not available for this php version 7. Any suggestions?

**Comment by dzuelke** [comment]
You can't until the developers release a version that works with PHP 7; it's only available for PHP 5, see https://pecl.php.net/package/memcached

You can follow dev progress at https://github.com/php-memcached-dev/php-memcached, and read up on status history at https://github.com/php-memcached-dev/php-memcached/issues/213

Once there is a stable release, we will of course make it available ASAP.

Also see #168 (and consider looking into Redis as an alternative).

**Comment by vlahanas** [comment]
that's a lot of useful info @dzuelke  , thanks!

**Comment by IvoPereira** [comment]
@dzuelke it appears that PHP7 support has been implemented.

Is there any chance you implement this in a near future?

**Comment by dzuelke** [comment]
You can simply do `composer install --ignore-platform-reqs` (as is explained in the blue box in the section I linked to), or put `ext-memcached` into `config.platform` (https://getcomposer.org/doc/06-config.md#platform), @IvoPereira...
