### ISSUE TITLE
Update ext-imagick to allow use of PHP 7.1

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#212]
Now ```3.4.3``` is available as stable release of Imagick with support for PHP 7.1, would it be an idea to adopt this so it can be added to the [list of supported PHP 7.1 extensions](https://devcenter.heroku.com/articles/php-support#php-7-1)?

https://pecl.php.net/package/imagick
https://github.com/mkoppanen/imagick/issues/183

**Comment by dzuelke** [comment]
Of course. It's already built and published to the dev platform repo, but we're usually not rolling out updates before, or even on, weekends...

**Comment by holtkamp** [comment]
Ok, great!

>It's already built and published to the dev platform repo.

Is there a way I could have known / found out about this? Or... Is it even the proper place to submit an issue at?

**Comment by dzuelke** [comment]
Well, the commits are on the `develop` branch, and you could always act bravely and `heroku config:set HEROKU_PHP_PLATFORM_REPOSITORIES="- https://lang-php.s3.amazonaws.com/dist-cedar-14-develop/"` :), but in principle, this is the right place to ask.

I do monitor extension updates very closely though, so usually, it's safe to assume that an update is coming. Sometimes very quickly, sometimes it can take a week or two. In this case, I'm waiting until Thursday so I can roll out new PHP releases as well in one bigger update.

Thanks for your patience!
