### ISSUE TITLE
Heroku Mime Types

### ISSUE THREAD

**Issue by LaurentBrieu** [heroku/heroku-buildpack-php#213]
On https://github.com/heroku/heroku-buildpack-php/blob/master/conf/nginx/heroku.conf.php#L2, you are trying to include a mime.types file, which doesn't seems to exist in the repository.

Is it normal ? Do we have to add a "mime.types" file in the root of our project, like Procfile, to get it working ?

**Comment by dzuelke** [comment]
That file ships with every distribution of Nginx. Includes are always relative to the base config directory defined at compile time, so it'll get picked up.
