### ISSUE TITLE
Broken HTTP links should lead to readable errors

### ISSUE THREAD

**Issue by lmars** [heroku/heroku-buildpack-php#216]
Using tag `v117` of this buildpack does not currently work because there is a broken reference to PHP `7.0.14` [here](https://github.com/heroku/heroku-buildpack-php/blob/v117/bin/compile#L100):

```
$ curl -fsSLo /dev/null https://lang-php.s3.amazonaws.com/dist-cedar-14-stable/php-min-7.0.14.tar.gz                         
curl: (22) The requested URL returned error: 404 Not Found
```

It seems the intention of the code is to print an error in this case, but a lack of the `--fail` flag does not lead `curl` to exit non-zero for a 404, so should probably be added there along with `--show-error`.

Also, is there a reason `7.0.14` was yanked so soon after being released (2 months ago)?

Ref https://github.com/flynn/flynn/issues/3934.

**Comment by lmars** [comment]
FYI the actual error seen:

```
-----> Bootstrapping...
remote: 
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
```

**Comment by dzuelke** [comment]
7.0.14 contains security vulnerabilities. It's not really a big deal for bootstrapping, but we generally like to keep things tidy.
