### ISSUE TITLE
allow .well-known/acme-challenge access

### ISSUE THREAD

**Issue by ivoba** [heroku/heroku-buildpack-php#218]
I tried to enable lets-encrypt on my php-app but i cant make the` /.well-known/acme-challenge/` path accessable. I keep getting 403 errors.

I guess this is because of restriction to hidden files in https://github.com/heroku/heroku-buildpack-php/blob/master/conf/nginx/heroku.conf.php#L62

I added a custom nginx conf in Procfile:

`web: vendor/bin/heroku-php-nginx -C nginx.conf web/`

and added all kinds of nginx configurations like 

```
location ~ ^ /.well-known/ {
  allow all;
  auth_basic off;
}
```

but none of them worked, so i guess i cant overwrite the restriction.

How can i do this?

**Comment by dzuelke** [comment]
This should work:

```
location ^~ /.well-known/ {
    allow all;
}
```

If you also need to run PHP code in there, add a `try_files @heroku-fcgi @heroku-fcgi;`.

**Comment by connor11528** [comment]
@dzuelke I am getting the same 403 error for a Laravel app using default **public/.htacess** file

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

</IfModule>
```

My **Procfile** is below. I am following steps to get SSL cert w/ certbot.

```
web: vendor/bin/heroku-php-apache2 public/
```

Do you know how I would whitelist the `/.well-known/acme-challenge/` route in the **.htaccess** file?

**Comment by dzuelke** [comment]
IIRC this works, in `.well-known/.htaccess`:

```
<FilesMatch ".*">
    Require all granted
</FilesMatch>
```

But... you know Heroku now handles Let's Encrypt for you, right? :) https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by connor11528** [comment]
did not know this... thanks!

solution for me was dropping a file in my public directory with the correct keys. in the future will likely use the @heroku-tools platform
