### ISSUE TITLE
Custom compile step results will not be included in classmap by default

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#219]
A [custom compile step](https://devcenter.heroku.com/articles/php-support#custom-compile-step) can be used to prepare an application for use. This is triggered here:
https://github.com/heroku/heroku-buildpack-php/blob/e0499a7fdffd56f46534a037a6c48d65cef4e645/bin/compile#L259

However, suppose a number of PHP proxy files are generated (Doctrine proxies, or proxies of lazy loaded dependency injection container resources), these PHP files / classes do not end up in the classmap since that was already dumped and optimized here
https://github.com/heroku/heroku-buildpack-php/blob/e0499a7fdffd56f46534a037a6c48d65cef4e645/bin/compile#L253

Would it be an idea to execute another`composer dump-autoload --optimize`? 

Now I think if it, one can also use that as a compile step:

```
{
  "scripts": {
    "compile": [
      "php doctrine.php orm:generate:proxies",
      "composer dump-autoload --optimize"
    ]
  }
}
```

**UPDATE**
Just tested the approach to end the compile scripts with "composer dump-autoload --optimize", this works, only the references in the generated classmap the point to a temporary path:

`Warning: require_once(/tmp/build_18348cdfb20f5df4fd55187698260833/myApplication/File.php): failed to open stream: No such file or directory in`

Is there a way to prevent this?

**Comment by dzuelke** [comment]
Yea, don't use the optimize flag ;)

It doesn't create portable class maps, so that's just what it is, not much you can do. That's why that flag is also not the default.

**Comment by holtkamp** [comment]
>Yea, don't use the optimize flag ;)

mm, sounds reasonable, however, just tried it with `composer dump-autoload`, same result. Note that my `composer.json` config section does not contain `optimize-autoloader: true` as well...

**Comment by holtkamp** [comment]
Well, I will just leave the dump-autoload part out and rely on the APCu optimization, as described here: https://github.com/composer/composer/blob/master/doc/articles/autoloader-optimization.md#optimization-level-2b-apcu-cache

**Comment by dzuelke** [comment]
Do you have a super old `composer.phar` in your project root or something?

I get no absolute paths even when dumping optimized autoloaders:

```php
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Monolog\\ErrorHandler' => $vendorDir . '/monolog/monolog/src/Monolog/ErrorHandler.php',
…
```

**Comment by holtkamp** [comment]
>I get no absolute paths even when dumping optimized autoloaders:
indeed, that is what I found weird as well, think it has nothing to do with composer but with the generation of the proxies. I reverted my plan to use the `compile` step, which is a bit too vendor specific as well. Now the generation of proxies happens before pushing it to Heroku and that works. Thanks for your time!

**Comment by holtkamp** [comment]
**UPDATE: problem solved, .ini configuration files were cached in volatile .php files on non-development environments**

Since each time the proxies I am talking about above are generated, some autogenerated property names of the proxies change. This behaviour is intended and not likely to be changed as discussed here: 

https://github.com/Ocramius/ProxyManager/issues/367

By generating the proxies (and thereby changing the content) BEFORE pushing the code to Heroku, this results in all proxies being committed and pushed to Heroku on each deploy. Quite useless and increasing the deployment time with about 3 minutes.

So I was back at looking into the `compile` step to generate the proxies when the code is being deployed to Heroku. The problem was, when generating the proxies in the `compile` steps, this kept resulting in "class not found" errors for a specific file: `/tmp/build_935ba0260f34fd67f1958a2c8c87169e/application/Bootstrap.php`

Eventually I found the cause. Since parsing of .ini files is "expensive": on non-development / production environments we parse and serialise them  to a PHP array and write it to a file, this way it can be opcode cached. The script that is used to start the proxy generation during the `compile` step, also bootstraps the application and runs in the production environment, so this triggered the generation of PHP representations of the .ini files. One of the configuration settings in a application.ini file, is which file to use as a 'Bootstrap' file. The absolute path of that file (`/tmp/build_935ba0260f34fd67f1958a2c8c87169e/application/Bootstrap.php`) was used in the generated PHP file. After the compilation step, this bootstrap file does not exist anymore, but the application still uses it, resulting in the mentioned error.

By having the `compile` step explicitly remove this file, this behaviour is circumvented:

```json
  "scripts": {
    "compile": [
      "php --define memory_limit=1024M application/console.php dependencyInjectionContainer:generateProxies",
      "rm data/application.ini.cached.php",
      "composer dump-autoload --optimize"
    ],
}
```

As you can see the `--optimize` flag can be used as well, as @dzuelke brought up: https://github.com/heroku/heroku-buildpack-php/issues/219#issuecomment-285980868

Maybe this info helps other people encountering / understanding comparing behaviour 😄
