### ISSUE TITLE
Review Apps is failed to create new instance when `env` is set in `app.json` file?

### ISSUE THREAD

**Issue by feryardiant** [heroku/heroku-buildpack-php#227]
First of all, apologize if this issue is belong to php buildpack, I just don't have idea where to ask.

Well, recently I just try the [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) feature & notice an issue that the worker (or something that create new instance for review automaticaly) is always fails to create new server instance when I set `env` key in my `app.json` file.

Here my scenario.

1. Let's say I've already create new Laravel project & push it to heroku.
1. I create `app.json` file and add this line of codes

   ```json
   {
     "name": "Laravel Project",
     "image": "heroku/php",
     "scripts": {
       "postdeploy": "php artisan migrate --force"
     }
   }
   ```

1. I create `Procfile` file and add this line

   ```
   web: vendor/bin/heroku-php-nginx -C custom-nginx.conf -i custom-php.ini public/
   ```

1. Push latest changes to heroku & enable Review Apps feature to my pipeline
1. I create new branch that contain some fixes & make a pull request,
1. I see my pipeline automaticaly create new server instance for my pull request, but it's failed to deploy due to database configuration is not set yet.
   
   ![image](https://cloud.githubusercontent.com/assets/508665/25577707/a7a4e204-2e92-11e7-9af2-5f520eb7849c.png)

1. Now, I need to add [`env`](https://devcenter.heroku.com/articles/app-json-schema#env) key to my `app.json` and add my database configuration.

   ```json
   {
     "name": "Laravel Project",
     "image": "heroku/php",
     "scripts": {
       "postdeploy": "php artisan migrate --force"
     },
     "env": {
       "APP_ENV": "staging",
       "DB_CONNECTION": "sqlite"
     }
   }
   ```

1. But, when I push it heroku couldn't create the new server instance & I can't see any error log or something that tell me information about what happen. I can only see **Create Review App** button on my pipeline

   ![image](https://cloud.githubusercontent.com/assets/508665/25577881/ad76d560-2e93-11e7-83aa-799d55ef7544.png)

   and, multiple _deployment request_ on my github PR.

   ![image](https://cloud.githubusercontent.com/assets/508665/25577922/17021422-2e94-11e7-83f0-e72b90abc3f1.png)

There's something missing from my config? or anyone have solution for me?

Thanks & sorry for my english.

**Comment by dzuelke** [comment]
SQLite won't work. You need to use e.g. Postgres. The reason is that your `php artisan migrate` command runs on a one-off dyno, and then the app starts on another, isolated, dyno, where the database doesn't exist. Dynos are isolated, share-nothing units that don't share a file system.

Change your DB use to Postgres, and add the "`heroku-postgresql`" add-on to `app.json`.
