### ISSUE TITLE
Potential GPL violation

### ISSUE THREAD

**Issue by tdmalone** [heroku/heroku-buildpack-php#232]
Hi there,

My own project depends on `heroku-buildpack-php` (as an aside, I'm not sure if I'm _meant_ to include that as a dev dependency in composer, but given my `Procfile` has it I figured I should). Anyway, I did a license scan on my project, and it found a potential violation: it turns out heroku-buildpack-php depends on (and integrates with) [s3cmd](https://pypi.python.org/pypi/s3cmd), which is licensed under GPLv2. Due to the viral nature of the GPL, this potentially means that heroku-buildback-php needs to be licensed under a compatible copyleft license (which really only leaves GPLv2 or 3), rather than MIT.

My understanding is that it would come down to how tightly or loosely coupled `s3cmd` is with this project.

From [the GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins):

> **When is a program and its plug-ins considered a single combined program?** (#GPLPlugins)
> It depends on how the main program invokes its plug-ins. If the main program uses fork and exec to invoke plug-ins, and they establish intimate communication by sharing complex data structures, or shipping complex data structures back and forth, that can make them one single combined program. A main program that uses simple fork and exec to invoke plug-ins and does not establish intimate communication between them results in the plug-ins being a separate program.

([this FAQ question](https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation) is also relevant)

s3cmd [is called in a couple of functions](https://github.com/heroku/heroku-buildpack-php/search?q=s3cmd) in this project's source, and [one of those functions](https://github.com/heroku/heroku-buildpack-php/search?q=generate_manifest_cmd) is invoked quite a lot.

I am not sure if this amounts to tight coupling as far as the GPL is concerned, particularly because I don't understand exactly how the build process works, but it _appears_ that heroku-buildpack-php would not work without s3cmd, and thus is pretty dependent on it.

Anyway, I'd appreciate your input on this, and if it's judged to be a separate program perhaps clarifying this situation in the README would be good.

Thanks for your consideration!

**Comment by dzuelke** [comment]
It's not a violation. The buildpack merely invokes `s3cmd` through shell scripts, and only in the utilities that aid in building platform packages. It can perform its key functionality perfectly fine without `s3cmd`, and it doesn't "share or ship back and forth complex data structures". It also doesn't bundle `s3cmd`.

By your logic, any non-GPL shell script that invokes `cd` or `cat` would also violate the GPL when run on a Linux system.
