### ISSUE TITLE
hhvm and deps installed over HTTP with no additional validation

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-php#233]
The hhvm install script downloads the .deb archives for hhvm and its dependencies over HTTP using curl, which are then consumed directly by dpkg (which does not perform signature validation):
https://github.com/heroku/heroku-buildpack-php/blob/b5c4a0b77a725c4ab9dc1736e5a8217824790093/support/build/hhvm#L25-L67

The `ppa.launchpad.net` and `mirrors.kernel.org` repositories support HTTPS, so should be fine to just `s/http:/https:/`.

However `dl.hhvm.com` does not:
```
$ curl -I https://dl.hhvm.com/ubuntu/pool/main/h/hhvm/hhvm_3.18.3~trusty_amd64.deb
curl: (51) SSL: no alternative certificate subject name matches target host name 'dl.hhvm.com'
```
...so presumably would need separate hash (or ideally signature) verification instead.

**Comment by dzuelke** [comment]
Closing this as HHVM is no longer supported.
