### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#234]
Hi,

Shouldn't this get updates? PHP 7.1.6 is already out and this one's still on 7.1.3 for example.

Thanks

**Comment by dzuelke** [comment]
Yes, of course; new runtimes will land next Thursday when they're released upstream. Thank you for your patience.

**Comment by boboldehampsink** [comment]
Sorry, when will this be?

**Comment by dzuelke** [comment]
Out now! https://devcenter.heroku.com/changelog-items/1211
