### ISSUE TITLE
ext-intl is missing

### ISSUE THREAD

**Issue by vlahanas** [heroku/heroku-buildpack-php#237]
Hello,

Lately, i keep receiving this error in a php app that i have on heroku:

The requested PHP extension ext-intl * is missing from your system. Install or enable PHP's intl extension.

The thing is that i have maintained the same setup and composer files for quite a long, and i have no issues will building. Moreover, in between the failed build attempts, one was successful. Any ideas would be very helpful!

**Comment by dzuelke** [comment]
Fixed: https://status.heroku.com/incidents/1254

**Comment by vlahanas** [comment]
Thank you, indeed it was fixed! 

Sorry for opening an issue, there was no official heroku status when i posted here
