### ISSUE TITLE
Missing extensions for dev dependencies cause regular builds to fail

### ISSUE THREAD

**Issue by dzuelke** [heroku/heroku-buildpack-php#240]
```
$ git push heroku master
…
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote: -----> Installing platform packages...
remote: 
remote:  !     ERROR: Failed to install system packages.
remote:        
remote:        Your platform requirements (for runtimes and extensions) could
remote:        not be resolved to an installable set of dependencies, or a
remote:        repository was unreachable.
remote:        
remote:        Full error information from installation attempt:
remote:        
remote:        > Loading repositories with available runtimes and extensions
remote:        > Updating dependencies
remote:        > Your requirements could not be resolved to an installable set of packages.
remote:        > 
remote:        >   Problem 1
remote:        >     - Installation request for etsy/phan 0.9.4 -> satisfiable by etsy/phan[0.9.4].
remote:        >     - etsy/phan 0.9.4 requires ext-ast ^0.1.4 -> no matching package found.
remote:        > 
…
```

The reason is that no lock file is present for the "platform" `composer.json` that gets written based on the app `composer.lock`, and on `composer install`, Composer has to generate a full graph of dependencies, including for `require-dev`, even though only non-dev dependencies get installed.

The `require-dev` section gets copied for Heroku CI, where the build is done without the `--no-dev` flag.

The fix is to not evaluate `require-dev` at all in `platform.php` if we're in a regular build.

**Comment by dzuelke** [comment]
Fixing this may mean that regular and CI builds might get different versions of things, e.g. if an extension in `require-dev` isn't available for the otherwise latest possible PHP version. Must consider whether or not that's acceptable.

**Comment by morozov** [comment]
@dzuelke I think it would be acceptable if ignoring a missing dependency didn't cause choosing a different PHP version. In other words, if a development dependency is not available in any PHP version, it's safe to ignore it.

**Comment by dzuelke** [comment]
That's really hard to do though, because of how we're relying on the Composer dependency solver to build us a graph of things to install; CI builds also still would fail.

Composer should maybe have a `--ignore-platform-dev-reqs` switch, that'd solve it...

**Comment by laszlof** [comment]
Just ran into this issue myself. Cant deploy with `phan/phan` in require-dev. Is there any solution for this? Even if we can pass additional composer flags via environment would help.

**Comment by morozov** [comment]
@Seldaek not sure how familiar you are with how Heroku installs PHP applications, but could you answer https://github.com/heroku/heroku-buildpack-php/issues/240#issuecomment-330385684?

**Comment by laszlof** [comment]
Looks like the API is down right now. Was going to try a couple things myself to see if I could solve it, but the builds fail when trying to push to heroku. :(

**Comment by dzuelke** [comment]
@morozov @laszlof wanna try the develop branch and tell me if ef81ae4 fixes it?

```ShellSession
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-php.git#develop
```

**Comment by laszlof** [comment]
@dzuelke Excellent! Worked like a charm. Thanks!

**Comment by morozov** [comment]
Works for me too. Thank you!

**Comment by dzuelke** [comment]
You guys are on fire. Thanks for the quick replies!
