### ISSUE TITLE
nginx: [emerg] invalid parameter "2400:cb00::/32"

### ISSUE THREAD

**Issue by tillkruss** [heroku/heroku-buildpack-php#241]
Is there any chance we can upgrade Nginx or the ngx_http_realip_module module to support IPv6 addresses?

> IPv6 addresses are supported starting from versions 1.3.0 and 1.2.1.
> http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by dzuelke** [comment]
This is for local execution, right?

**Comment by tillkruss** [comment]
I'm just adding it to the `server` block in my custom `nginx.conf`.

```
web: vendor/bin/heroku-php-nginx -C nginx.conf public/
```

**Comment by dzuelke** [comment]
Adding what?

**Comment by tillkruss** [comment]
Ah, sorry 😄

Cloudflare IP addresses.

```
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/12;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 199.27.128.0/21;
# set_real_ip_from 2400:cb00::/32;
# set_real_ip_from 2606:4700::/32;
# set_real_ip_from 2803:f800::/32;
# set_real_ip_from 2405:b500::/32;
# set_real_ip_from 2405:8100::/32;
# set_real_ip_from 2c0f:f248::/32;
# set_real_ip_from 2a06:98c0::/29;
```

**Comment by chrisnew** [comment]
This would actually work if the nginx being used here was compiled with `--with-ipv6` flag.

**Comment by dzuelke** [comment]
Well, Heroku's routing doesn't currently support IPv6, so... 😬

**Comment by chrisnew** [comment]
That’s a pity to not support modern protocols. However, I’m preparing a pull request for that over the next days.

**Comment by dzuelke** [comment]
Don't worry about it, we're upgrading to a new Nginx version very soon anyway, and we won't be touching the old one.

The IPv4 restriction has to do with the underlying infrastructure; we run on AWS, and e.g. Classic ELBs in EC2 VPCs do not support IPv6. It makes no practical difference anyway, as all IPv6 clients have IPv4 capabilities through some kind of transition mechanism (NAT64, 6rd, DS-Lite, …).
