### ISSUE TITLE
PHP assertions should be set in prod mode

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#242]
Currently, the php.ini in the buildpack does not configure `zend.assertions`, which means that it is set to `1`, which runs assertions.
But the recommended production mode is to set it to `-1`, so that assertions are removed at compile time (see http://php.net/manual/en/function.assert.php#function.assert.expectations).
I suggest using the recommended production mode in the buildpack config

**Comment by stof** [comment]
Note: if possible, you should keep it set to `1` when running on Heroku CI

**Comment by dzuelke** [comment]
Working on correcting some other INI defaults so they line up with each version's `php.ini-production`, @stof... do you think we can, for now, get away with setting it to `-1` across the board, and figure out CI later?

**Comment by stof** [comment]
Well, that would be a good first step to optimize for production.

The only drawback I see for CI is that it is not possible to use a `ini_set` at runtime in your testsuite bootstrap to move away from `-1`. But CI could still be figured out later (I'm not using CI myself, so I'm quite OK with dealing with it later)
