### ISSUE TITLE
ext-geoip and ext-ssh2 please help me!!!

### ISSUE THREAD

**Issue by tidus30691nexus5** [heroku/heroku-buildpack-php#243]
Please help me how to install module geoip and ssh2 on php in heroku.

**Comment by dzuelke** [comment]
These extensions are currently not supported on Heroku. You can maintain your own repository of extension builds, see https://github.com/heroku/heroku-buildpack-php/blob/master/README.md#custom-platform-repositories and https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/README.md and as inspiration for how to do this all, https://github.com/Incenteev/heroku-php-exts
