### ISSUE TITLE
Failed to download minimal PHP for bootstrapping

### ISSUE THREAD

**Issue by mochnatiy** [heroku/heroku-buildpack-php#251]
Hi everyone! I use dokku with this buildpack (for simple wordpress app) and yesterday I've got a message when deploying an app:

-----> Cleaning up...
-----> Building wordpress from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> PHP app detected
-----> Bootstrapping...
       
       !     ERROR: Failed to download minimal PHP for bootstrapping.
       Please try again, or contact support if this problem persists.

I use amazon ec2 server, no problems with internet there. What it could be?
My .buildpacks file contains:

https://github.com/heroku/heroku-buildpack-php.git#v125

**Comment by mikaelbartlett** [comment]
I bumped version to v127 to test in our staging and that works.

**Comment by mochnatiy** [comment]
Thanks! I did the same thing and it works now.

**Comment by dzuelke** [comment]
#249
