### ISSUE TITLE
Disable Apache Access Logs

### ISSUE THREAD

**Issue by thorstenspringhart** [heroku/heroku-buildpack-php#252]
Hi,
I am using the heroku-php-apache2 boot script and want to disable the access logging of the apache2.

I added `CustomLog /dev/null combined` to my conf file but this did not disabled the logging.

Is there a way to disable the apache access logs? The heroku router logs are sufficient for my usecase.

**Comment by dzuelke** [comment]
The format used is named `heroku`, not `custom`!
