### ISSUE TITLE
Composer 1.6.0 and 1.6.1 breaks the autoloader

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#254]
See https://github.com/composer/composer/issues/6977

1.6.2 seems to fix it

**Comment by tillkruss** [comment]
Same issue here. This is critical, we can't deploy any applications.

**Comment by tillkruss** [comment]
We are seeing the following issue:

```
Class 'CF\WordPress\Hooks' not found
```

See https://github.com/cloudflare/Cloudflare-WordPress/issues/209

**Comment by dzuelke** [comment]
Thanks for the report; fixed in v129 via 8e16fb8
