### ISSUE TITLE
Xhprof support

### ISSUE THREAD

**Issue by blacksonic** [heroku/heroku-buildpack-php#257]
Is it possible to add Xhprof support?
Currently only Blackfire is available for profiling, but it is not fully integrated with Heroku (no SSO, no billing)

**Comment by dzuelke** [comment]
Xhprof is not maintained anymore and doesn't support PHP 7. Blackfire works really well, and you can also use Tideways (https://tideways.io/profiler/article/35-installation-on-php#heroku).
