### ISSUE TITLE
Wrong version of libsodium installed (libsodium18 instead of libsodium23)

### ISSUE THREAD

**Issue by iSDP** [heroku/heroku-buildpack-php#261]
It appears the sodium library version is outdated.

This causes issues for applications that require newer functions (like built in Argon2 support)

Currently used version: `1.0.8` / `libsodium18`
Latest release: `1.0.16` / `libsodium23`

Example: symfony/symfony#26179

**Comment by stof** [comment]
This is already working fine for me (my application requires more extensions than the ones available in php-min, and works fine).

Please provide more details about the issue you face.

**Comment by iSDP** [comment]
```
remote: =====> Detected Framework: PHP
remote: -----> Bootstrapping...
remote: -----> Installing platform packages...
remote:        - php (7.2.2)
remote:        - ext-intl (bundled with php)
remote:        - ext-mbstring (bundled with php)
remote:        - ext-sodium (bundled with php)
remote:        - apache (2.4.29)
remote:        - nginx (1.8.1)
remote: -----> Installing dependencies...
remote:        Composer version 1.6.3 2018-01-31 16:28:17
remote:        Loading composer repositories with package information
remote:        Installing dependencies from lock file
remote:        Package operations: 73 installs, 0 updates, 0 removals
remote:        - Installing ocramius/package-versions (1.3.0): Loading from cache
remote:        - Installing symfony/flex (v1.0.68): Loading from cache
remote:        - Installing doctrine/lexer (v1.0.1): Loading from cache
remote:        - Installing doctrine/annotations (v1.6.0): Loading from cache
remote:        - Installing doctrine/collections (v1.5.0): Loading from cache
remote:        - Installing symfony/polyfill-mbstring (v1.7.0): Loading from cache
remote:        - Installing doctrine/inflector (v1.3.0): Loading from cache
remote:        - Installing doctrine/cache (v1.7.1): Loading from cache
remote:        - Installing doctrine/common (v2.8.1): Loading from cache
remote:        - Installing symfony/doctrine-bridge (v4.0.4): Loading from cache
remote:        - Installing doctrine/doctrine-cache-bundle (1.3.2): Loading from cache
remote:        - Installing doctrine/instantiator (1.1.0): Loading from cache
remote:        - Installing symfony/yaml (v4.0.4): Loading from cache
remote:        - Installing symfony/console (v4.0.4): Loading from cache
remote:        - Installing zendframework/zend-eventmanager (3.2.0): Loading from cache
remote:        - Installing zendframework/zend-code (3.3.0): Loading from cache
remote:        - Installing ocramius/proxy-manager (2.2.0): Loading from cache
remote:        - Installing doctrine/dbal (v2.6.3): Loading from cache
remote:        - Installing doctrine/migrations (v1.6.2): Loading from cache
remote:        - Installing symfony/routing (v4.0.4): Loading from cache
remote:        - Installing symfony/http-foundation (v4.0.4): Loading from cache
remote:        - Installing symfony/event-dispatcher (v4.0.4): Loading from cache
remote:        - Installing psr/log (1.0.2): Loading from cache
remote:        - Installing symfony/debug (v4.0.4): Loading from cache
remote:        - Installing symfony/http-kernel (v4.0.4): Loading from cache
remote:        - Installing symfony/finder (v4.0.4): Loading from cache
remote:        - Installing symfony/filesystem (v4.0.4): Loading from cache
remote:        - Installing psr/container (1.0.0): Loading from cache
remote:        - Installing symfony/dependency-injection (v4.0.4): Loading from cache
remote:        - Installing symfony/config (v4.0.4): Loading from cache
remote:        - Installing psr/simple-cache (1.0.0): Loading from cache
remote:        - Installing psr/cache (1.0.1): Loading from cache
remote:        - Installing symfony/cache (v4.0.4): Loading from cache
remote:        - Installing symfony/framework-bundle (v4.0.4): Loading from cache
remote:        - Installing symfony/expression-language (v4.0.4): Loading from cache
remote:        - Installing psr/http-message (1.0.1): Loading from cache
remote:        - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
remote:        - Installing guzzlehttp/promises (v1.3.1): Loading from cache
remote:        - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
remote:        - Installing eightpoints/guzzle-bundle (7.3.0): Loading from cache
remote:        - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
remote:        - Installing sensio/framework-extra-bundle (v5.1.6): Loading from cache
remote:        - Installing composer/ca-bundle (1.1.0): Loading from cache
remote:        - Installing sensiolabs/security-checker (v4.1.7): Loading from cache
remote:        - Installing sentry/sentry (1.8.3): Loading from cache
remote:        - Installing symfony/asset (v4.0.4): Loading from cache
remote:        - Installing symfony/inflector (v4.0.4): Loading from cache
remote:        - Installing symfony/property-access (v4.0.4): Loading from cache
remote:        - Installing symfony/options-resolver (v4.0.4): Loading from cache
remote:        - Installing symfony/intl (v4.0.4): Loading from cache
remote:        - Installing symfony/polyfill-intl-icu (v1.7.0): Loading from cache
remote:        - Installing symfony/form (v4.0.4): Loading from cache
remote:        - Installing symfony/maker-bundle (v1.0.2): Loading from cache
remote:        - Installing monolog/monolog (1.23.0): Loading from cache
remote:        - Installing symfony/monolog-bridge (v4.0.4): Loading from cache
remote:        - Installing symfony/monolog-bundle (v3.1.2): Loading from cache
remote:        - Installing doctrine/orm (v2.6.0): Loading from cache
remote:        - Installing doctrine/doctrine-bundle (1.8.1): Loading from cache
remote:        - Installing doctrine/doctrine-migrations-bundle (v1.3.1): Loading from cache
remote:        - Installing symfony/orm-pack (v1.0.5): Loading from cache
remote:        - Installing symfony/security (v4.0.4): Loading from cache
remote:        - Installing symfony/security-bundle (v4.0.4): Loading from cache
remote:        - Installing symfony/templating (v4.0.4): Loading from cache
remote:        - Installing twig/twig (v2.4.4): Loading from cache
remote:        - Installing symfony/twig-bridge (v4.0.4): Loading from cache
remote:        - Installing symfony/twig-bundle (v4.0.4): Loading from cache
remote:        - Installing symfony/translation (v4.0.4): Loading from cache
remote:        - Installing symfony/validator (v4.0.4): Loading from cache
remote:        - Installing symfony/process (v4.0.4): Loading from cache
remote:        - Installing symfony/web-server-bundle (v4.0.4): Loading from cache
remote:        - Installing symfony/webpack-encore-pack (v1.0.2): Loading from cache
remote:        Generating optimized autoload files
remote:        ocramius/package-versions:  Generating version class...
remote:        ocramius/package-versions: ...done generating version class
remote:        Executing script cache:clear [KO]
remote:        [KO]
remote:        Script cache:clear returned with error code 1
remote:        !!
remote:        !!  In SecurityExtension.php line 512:
remote:        !!
remote:        !!    Argon2i algorithm is not supported. Please install the libsodium extension
remote:        !!    or upgrade to PHP 7.2+.
remote:        !!
remote:        !!
remote:        !!
```

**Comment by iSDP** [comment]
```
remote: -----> Installing platform packages...
remote:        - php (7.2.2)
remote:        - ext-intl (bundled with php)
remote:        - ext-mbstring (bundled with php)
remote:        - ext-sodium (bundled with php)
remote:        - apache (2.4.29)
remote:        - nginx (1.8.1)
remote: -----> Listing installed extensions
remote:        Core
remote:        date
remote:        libxml
remote:        openssl
remote:        pcre
remote:        zlib
remote:        bz2
remote:        ctype
remote:        curl
remote:        dom
remote:        fileinfo
remote:        filter
remote:        hash
remote:        iconv
remote:        json
remote:        SPL
remote:        PDO
remote:        session
remote:        pdo_pgsql
remote:        pgsql
remote:        standard
remote:        posix
remote:        readline
remote:        Reflection
remote:        Phar
remote:        SimpleXML
remote:        sockets
remote:        mysqlnd
remote:        mysqli
remote:        tokenizer
remote:        xml
remote:        xmlreader
remote:        xmlwriter
remote:        zip
remote:        pdo_mysql
remote:        intl
remote:        mbstring
remote:        sodium
remote:        Zend OPcache
remote: -----> Checking Argon2i
remote:        Argon2i Not Available
```
Modded the buildpack to show extensions and check if `PASSWORD_ARGON2I` is defined.
Sodium is loaded but `PASSWORD_ARGON2I` is not

**Comment by iSDP** [comment]
@stof @dzuelke created a PR to fix this issue

**Comment by iSDP** [comment]
Found out what was wrong, it's using the wrong libsodium version 🤔

**Comment by dzuelke** [comment]
Sorry, I am confused here. The `sodium` extension and `libargon2` support are usually independent. There is no `libsodium2` support at the moment because that library is not supported in Ubuntu 16.04.

**Comment by dzuelke** [comment]
From https://github.com/symfony/symfony/issues/26179 it sounds like you have your Symfony cache checked into Git, and that's what's causing the problem, since it was created on your local box which has argon2 support!?

**Comment by iSDP** [comment]
@dzuelke libsodium 1.0.8 doesn't have Argon2 support, 1.0.9 does.
libsodium23 uses v1.0.16

libsodium should be built from source instead then.

**Comment by dzuelke** [comment]
Source builds won't be happening. Crypto and security libraries are always used from the underlying stack image, as that's the only way we can patch them for all applications without rebuilds.

With the new Ubuntu 18.04 LTS coming later this spring, we plan on providing a new stack image based on it, and that'll have libsodium version 1.0.16.

In the meantime, my recommendation (and the recommendation of our security team, which I have discussed this with previously), is to use `bcrypt`.

**Comment by dzuelke** [comment]
(FYI, the exception message from Symfony is a little misleading; `libsodium` isn't strictly necessary, as PHP 7.2, when built against `libargon2`, will also work).

**Comment by dzuelke** [comment]
@stof yeah there is no `libargon2` in Ubuntu LTS yet.

**Comment by iSDP** [comment]
`argon2` is preferred over `bcrypt` anyway.

If PHP7.2 is used it's only logical that Argon2 is available as well, so either remove sodium completely until the stack is updated or use the latest sodium version for security.

**Comment by iSDP** [comment]
Also, working on fixing up that error, there's a PR for that

**Comment by iSDP** [comment]
```
→ apt search libsodium
Sorting... Done
Full Text Search... Done
libsodium-dbg/xenial 1.0.8-5 amd64
  Network communication, cryptography and signaturing library - debug symbols

libsodium-dev/xenial 1.0.16-2+ubuntu16.04.1+deb.sury.org+3 amd64
  Network communication, cryptography and signaturing library - headers

libsodium18/xenial 1.0.8-5 amd64
  Network communication, cryptography and signaturing library

libsodium23/xenial,now 1.0.16-2+ubuntu16.04.1+deb.sury.org+3 amd64 [installed,automatic]
  Network communication, cryptography and signaturing library

python-libnacl/xenial-updates,xenial-updates 1.4.5-0ubuntu1 all
  Python 2 bindings for libsodium based on ctypes

python-nacl/xenial 1.0.1-1build1 amd64
  Python bindings to libsodium (Python 2)

python-nacl-doc/xenial,xenial 1.0.1-1build1 all
  Python bindings to libsodium (documentation)

python3-libnacl/xenial-updates,xenial-updates 1.4.5-0ubuntu1 all
  Python 3 bindings for libsodium based on ctypes

python3-nacl/xenial 1.0.1-1build1 amd64
  Python bindings to libsodium (Python 3)
```

On Ubuntu 16.04.

I'm using this PPA: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by dzuelke** [comment]
As it's significantly newer, argon2, unlike bcrypt or scrypt, has been under significantly less scrutiny so far.

The sodium extension exposes what the underlying library supports. Version 1.0.8 was specifically chosen as the minimum supported version for PHP 7.2 because there is widespread support for it in LTS distros.

**Comment by iSDP** [comment]
so it is possible to use `libsodium23` as long as that PPA is used, is that possible?

**Comment by dzuelke** [comment]
No, it is not possible; we cannot use third-party PPAs that we don't control for security and support reasons (Canonical won't support them, among other factors).

If you're absolutely set on using argon2i as the algorithm, couldn't you use https://github.com/paragonie/sodium_compat in the interim? That's automatically used by Symfony if available.

**Comment by dzuelke** [comment]
Another aside, just to clarify it (from https://github.com/symfony/symfony/issues/26179):

> They use php-min to run Composer, libsodium is not used there.

The `php-min` package is just what's used to run Composer to install PHP and all extensions based on your dependency graph. After that is complete, the regular `composer install` of course runs with your desired version of PHP (and all the extensions active), otherwise, the install would fail with version mismatches :)

**Comment by iSDP** [comment]
Yeah, found that out later, it got a bit late last night haha

Also, why can't libsodium be built from a stable source?

**Comment by dzuelke** [comment]
If we build our own `libsodium` (or `libargon2`) for inclusion in the PHP buildpack's own packages, then if there is a security issue in either (and that has happened; there were two attacks already in the past against the argon2 algorithm that were fixed in later versions), we can update the builds, but they won't be picked up until the next time each customer deploys.

Libraries that are part of the stack image, on the other hand, we can update centrally; the underlying boxes restart, and the applications that restart on top of that then use the fixed version (because, well, it's all dynamically linked).

We currently do not support any self-built libraries on the stack image; we rely solely on upstream vendors for security fixes, which often need to be backported; the whole idea of an LTS release (and the commercial-or-not support offered for them) is this "peace of mind".

Take `libsodium18`, for instance. Should a big vulnerability be found in libsodium, that'd be released as version 1.0.17. But you can't simply update existing applications to that version, since the ABI version is not 18 anymore, it's 23 (hence `libsodium23`), or maybe it would be 24 for v1.0.17. Applications that were built against, and thus now link against, `libsodium18`, would crash if the system now has `libsodium23`.

So the security fix needs to be analyzed, understood, and its effect backported to the old 1.0.8 version. That's what Debian and Ubuntu maintainers do routinely (and in case of LTS releases of either, for many years). And that's how we can guarantee stability for your apps: you deploy today, and it can keep running for years, with critical underlying system libraries receiving fixes in the background.

**Comment by iSDP** [comment]
Thank you for your lengthy explanation!

Understandably so, stability and safety are very important.

**Comment by paragonie-scott** [comment]
> If you're absolutely set on using argon2i as the algorithm, couldn't you use https://github.com/paragonie/sodium_compat in the interim? That's automatically used by Symfony if available.

Sodium_compat doesn't polyfill Argon2. https://github.com/paragonie/sodium_compat#features-excluded-from-this-polyfill

**Comment by dzuelke** [comment]
Be that as it may, the new heroku-18 stack has both argon2 support for PHP as well as libsodium23 (1.0.16), see also https://devcenter.heroku.com/changelog-items/1444, so this is no longer an issue :)
