### ISSUE TITLE
Enable Webpack Support For Merging of CSS & JS Files at During Build

### ISSUE THREAD

**Issue by chris-rutherfurd** [heroku/heroku-buildpack-php#272]
Webpack is a common tool for merging and minifying CSS and JS files at build time instead of needing to pollute the source repository with the bundled and minified built artifacts.

Suggesting to add webpack support to the PHP build pack reading a webpack config file from the repo root so that developers can bundle css and js files as part of the build process to add the bundled files to the slug.

**Comment by dzuelke** [comment]
No.

Simply use [multiple buildpacks](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) to have `heroku/nodejs` build first (where you install webpack), and `heroku/php` second (where you use the [compile step](https://devcenter.heroku.com/articles/php-support#custom-compile-step) to run webpack the way you want).
