### ISSUE TITLE
Support private packagist

### ISSUE THREAD

**Issue by neclimdul** [heroku/heroku-buildpack-php#275]
Similar to COMPOSER_GITHUB_OAUTH_TOKEN, it would be nice to have some way of logging in to private packagist instances during compile so composer can access private dependencies and/or use the private mirrors.

Something like:

```
composer config --global --auth http-basic.repo.packagist.com token $COMPOSER_PACKAGIST_TOKEN
```

**Comment by neclimdul** [comment]
Just noticed there is PR #225 because I searched issues not PRs... sorry.

I think #276 is a better approach so I'll leave these open.

**Comment by dzuelke** [comment]
I'm closing this for now; we can't add a magic proprietary env var for every permutation of service and auth method (think about people's custom domain GitHub installs etc).

The docs at https://devcenter.heroku.com/articles/php-support#private-repositories have been updated to give more examples on how to simply use `COMPOSER_AUTH` for this purpose.

Maybe one day Composer will have built-in support for magic env vars (see #225), but until then, a little bit of flattened JSON in an env var is not the end of the world IMO :)
