### ISSUE TITLE
Symfony 4 routing: only `/` page is working

### ISSUE THREAD

**Issue by jeroendesloovere** [heroku/heroku-buildpack-php#278]
Hi everybody,

When I deploy my "symfony 4" application to Heroku,
only the `/` page (route) is working.
Any other routes show the `Not Found` error.
<img width="445" alt="schermafbeelding 2018-05-07 om 14 19 32" src="https://user-images.githubusercontent.com/588616/39701499-b3393d0c-5201-11e8-8bfc-8a04594d4409.png">

Any ideas on how to solve this one?

**Comment by iwan-wijaya** [comment]
@jeroendesloovere 
HI, I was having a similar problem, here is how I get it working for now:

- First set document root by [creating a Procfile in your project directory](https://devcenter.heroku.com/articles/custom-php-settings#setting-the-document-root).

- Next, [setup your webserver](https://devcenter.heroku.com/articles/custom-php-settings#setting-the-document-root) by creating a `.htaccess` for Apache or `nginx_app.conf for Nginx`. If you are using Apache, you can also create the file by installing [Apache pack ](https://packagist.org/packages/symfony/apache-pack)

**Comment by jeroendesloovere** [comment]
Hi @iwan-wijaya, thanks for your answer.

What I already have:
**Procfile**
`web: $(composer config bin-dir)/heroku-php-apache2 public/`

Can you give me an example for the .htaccess file, I already have one and it does not work... :-(

**Comment by iwan-wijaya** [comment]
@jeroendesloovere 
You can use this one: https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/public/.htaccess

Or if you have Symfony Flex just run `composer require apache-pack`

**Comment by jeroendesloovere** [comment]
Closing this one...

**Comment by jeroendesloovere** [comment]
Thanks @iwan-wijaya

**Comment by dzuelke** [comment]
This is also documented here: https://devcenter.heroku.com/articles/deploying-symfony4#url-rewrites
