### ISSUE TITLE
PDO_ODBC/ ODBC extension for php

### ISSUE THREAD

**Issue by bhaveshsilversky** [heroku/heroku-buildpack-php#280]
I have installed unixODBC and unixODBC-dev and odbc driver(CDATA) using heroku-buildpack-apt
The issue I am facing for enabling odbc extension/ PDO_ODBC extension for php when I make request to the php script it gives me following error
Fatal error: Uncaught Error: Call to undefined function odbc_connect() in /app/odbs_query.php:17
Stack trace:
#0 {main}
  thrown in /app/odbs_query.php on line 17

For apt installation I am using following build pack and dependency added in the Aptfile, located at root of the source folder
heroku-buildpack-apt

I am using heroku official buildpack for php
Is it possible to add odbc/pdo_odbc extension if yes, Can you please provide some reference article?

**Comment by dzuelke** [comment]
Unfortunately, this is currently unsupported, and we have no plans of adding it. The extension has to be built at PHP build time, so that rules out using the Apt buildpack as a workaround unfortunately.

**Comment by bhaveshsilversky** [comment]
How to build the extension  at build time
I have tried the step provided custom packages 
but i was unable to compile the pdo_odbc extension
need help in compilation of pdo_odbc from pecl
