### ISSUE TITLE
folder permission and display error on heroku screen

### ISSUE THREAD

**Issue by ElanUtta** [heroku/heroku-buildpack-php#282]
Hi, I'm looking for a time to reconfigure the server according to my needs, it's hard to do this for buildpacks, since I get right from here. So I'm looking for a new solution, if anyone has it.

I would like the php errors to be displayed on the screen and to change permissions of folders that I created myself in heroku, to add photos to it.

**Comment by dzuelke** [comment]
You should not have `display_errors` on anywhere except in your development environment. You can see errors in `heroku logs`. If you want to change the setting anyway against this advice, you can simply `ini_set()` it or follow https://devcenter.heroku.com/articles/custom-php-settings#php-runtime-settings-ini-settings

You cannot store files on the dyno filesystem. The next time the dyno restarts (e.g. on deploy or every 24 hours), the filesystem is reset. It is also not shared between multiple dyno instances if you ever need to scale up. Store things in e.g. AWS S3 instead.
