### ISSUE TITLE
nginx is quite old

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#285]
This buildpack uses nginx 1.8.1. This is quite old. Current stable version of nginx is 1.14.

Thus, according to http://nginx.org/en/security_advisories.html, all versions before 1.12.1 are vulnerable.

**Comment by dzuelke** [comment]
Yup, aware; the problem is that Nginx 1.9.3 and later no longer allow multiple `http{}` blocks, and we're relying on that for assembling the config. Patches welcome ;)

**Comment by stof** [comment]
a solution might be to make the default nginx config (in `build/support` include all config files of a specific folder inside the `http` block, and then write the other imported files without this block.
This is similar to the way the `-C` file gets included inside the `server` block.

That might involve a BC break though for people using `-c` (as they would have to change their config file), which means it would have to be opt-in (maybe detecting whether `-c` is used or no)

**Comment by abarke** [comment]
Indeed. I think an nginx update is overdue. I would be nice to take advantage of the newer features that nginx offers aswell as security patches.

**Comment by tillkruss** [comment]
Anyone up for submitting a PR?

**Comment by abarke** [comment]
Please could Heroku spend some more time on patches, maintainance and communication? 

This repo is a bit lame given that its a core component of thousands if not millions of apps. Not something to expect from a Salesforce company 👎

**Comment by abarke** [comment]
Ping!

**Comment by stof** [comment]
Fixed by #329
