### ISSUE TITLE
Installing dev dependencies

### ISSUE THREAD

**Issue by denisvmedia** [heroku/heroku-buildpack-php#290]
Hi all,

I noticed that the buildpack checks `HEROKU_PHP_INSTALL_DEV` env var to allow or disallow installing dev dependencies. However when you export the env vars, you add this variable to the blacklist so that it's not exported. Why? And how to use it then?

Thanks.

**Comment by dzuelke** [comment]
It's internal only. If you need a dependency to build the app, it's not a dev dependency. Those are used mostly for testing, generating code at dev time, et cetera.

See #194.

**Comment by denisvmedia** [comment]
yes, and we need it to build an app for dev purposes. But ok, I get your point.
