### ISSUE TITLE
Valid PHP version requirements ignored

### ISSUE THREAD

**Issue by Chrisissorry** [heroku/heroku-buildpack-php#299]
Please see https://stackoverflow.com/questions/52672392/heroku-downgrade-php-version for reference.

Management summary:

Neither using `"php" : "^7.1"` nor `"php" : "~7.1"` works to set the desired PHP version, although this is indicated by [your documentation](https://devcenter.heroku.com/articles/php-support#selecting-a-runtime).

**Comment by dzuelke** [comment]
@Chrisissorry:

> Neither using `"php" : "^7.1"` nor `"php" : "~7.1"` works to set the desired PHP version, although this is indicated by [your documentation](
https://devcenter.heroku.com/articles/php-support#selecting-a-runtime).

That's not what the documentation says. The documentation says `^7.1.0`. There is a difference: https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators
