### ISSUE TITLE
PHP not detected 

### ISSUE THREAD

**Issue by masloord** [heroku/heroku-buildpack-php#303]
Laravel version : 5.5 

Error : 
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-php
remote:        
remote:  !     ERROR: Application not supported by this buildpack!
remote:  !     
remote:  !     The 'heroku/php' buildpack is set on this application, but was
remote:  !     unable to detect a PHP codebase.
remote:  !     
remote:  !     A PHP app on Heroku requires a 'composer.json' at the root of
remote:  !     the directory structure, or an 'index.php' for legacy behavior.
remote:  !     
remote:  !     If you are trying to deploy a PHP application, ensure that one
remote:  !     of these files is present at the top level directory.
remote:  !     
remote:  !     If you are trying to deploy an application written in another
remote:  !     language, you need to change the list of buildpacks set on your
remote:  !     Heroku app using the 'heroku buildpacks' command.
remote:  !     
remote:  !     For more information, refer to the following documentation:
remote:  !     https://devcenter.heroku.com/articles/buildpacks
remote:  !     https://devcenter.heroku.com/articles/php-support#activation
remote: 
remote: 
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed

Included Procfile with 
web: vendor/bin/heroku-php-apache2 public/

still doesnt work

**Comment by dzuelke** [comment]
Then you don't have a `composer.json` in your project, like the error message explains in great detail.

**Comment by librallaw** [comment]
How did u resove this issue?

**Comment by a123321998** [comment]
@librallaw You can read [this](https://help.heroku.com/1MC2J0GF/why-does-my-app-fail-to-detect-a-buildpack).
The project file need index.php.

**Comment by JoaoPedroMDP** [comment]
I am having the same issue, but my project have a index.php and also a composer.json
