### ISSUE TITLE
Facing issue locking php version.

### ISSUE THREAD

**Issue by rkamran1** [heroku/heroku-buildpack-php#313]
Hi

I am facing the issue from past 4 days. Since the php 7.3 added to this buildpacks.
My App was working fine till php 7.2 but since The buildpack updated I am facing this issue.

remote:        > php artisan optimize
remote:
remote:        In Container.php line 729:
remote:
remote:          Class get does not exist
remote:
remote:
remote:        Script php artisan optimize handling the post-install-cmd event returned with error code 1
remote:  !     WARNING: A post-install-cmd script terminated with an error
remote:
remote:  !     ERROR: Dependency installation failed!
remote:  !
remote:  !     The 'composer install' process failed with an error. The cause
remote:  !     may be the download or installation of packages, or a pre- or
remote:  !     post-install hook (e.g. a 'post-install-cmd' item in 'scripts')
remote:  !     in your 'composer.json'.
remote:  !
remote:  !     Typical error cases are out-of-date or missing parts of code,
remote:  !     timeouts when making external connections, or memory limits.
remote:  !
remote:  !     Check the above error output closely to determine the cause of
remote:  !     the problem, ensure the code you're pushing is functioning
remote:  !     properly, and that all local changes are committed correctly.
remote:  !
remote:  !     For more information on builds for PHP on Heroku, refer to
remote:  !     https://devcenter.heroku.com/articles/php-support
remote:  !
remote:  !     REMINDER: the following warnings were emitted during the build;
remote:  !     check the details above, as they may be related to this error:
remote:  !     - A post-install-cmd script terminated with an error

I tried to set the php to 7.2 by updating my .buildpacks file to this url 
https://github.com/heroku/heroku-buildpack-php#v146

but still it is fetching php 7.3

=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php
=====> Detected Framework: PHP
remote: -----> Bootstrapping...
remote: -----> Installing platform packages...
remote:        - php (7.3.0)
remote:        - ext-gd (bundled with php)
remote:        - ext-mbstring (bundled with php)
remote:        - nginx (1.8.1)
remote:        - apache (2.4.37)
remote: -----> Installing dependencies...

**Comment by dzuelke** [comment]
The buildpack revision has nothing to do with what platform packages you get.

You'll get the latest possible versions of everything according to your version requirements. If your `composer.json` allows installation of PHP 7.3, then you will get 7.3.0. You probably want to lock down your `require` for `php` to something like `~7.2.0`. See https://getcomposer.org/doc/articles/versions.md#tilde-version-range- and the big orange box in the docs at https://devcenter.heroku.com/articles/php-support#selecting-a-runtime

P.S.: please do not use `.buildpacks` and the deprecated `heroku-buildpack-multi`, but instead use the native platform functionality if you require more than one buildpack: https://devcenter.heroku.com/articles/buildpacks / https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app
