### ISSUE TITLE
php buildpack using php 7.3.0 when it should use php 7.2.x?

### ISSUE THREAD

**Issue by nettum** [heroku/heroku-buildpack-php#314]
Hi!
I just released a new version of an app and saw the following:
```
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote: -----> Installing platform packages...
remote:        - php (7.3.0)
```

My `composer.json` looks like this:
```
  "require": {
    ...
    "php": "~7.2",
    ...
  },
  "config": {
    "optimize-autoloader": true,
    "platform": {
      "php": "7.2"
    }
  },
```
Shoudn't this app run on php 7.2.x and not 7.3?  

Procfile: `web: vendor/bin/heroku-php-nginx -C nginx_app.conf -F fpm_custom.conf public/` and using 2 buildpacks:  `heroku/php` and `heroku/nodejs`  

Related to #313 ?

**Comment by dzuelke** [comment]
"`~7.2`" means "`7.*`, `7.2.0` or higher"... https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
