### ISSUE TITLE
Failed to download minimal PHP for bootstrapping

### ISSUE THREAD

**Issue by tugrulcan** [heroku/heroku-buildpack-php#318]
Hi! 
While deploying the app to Heroku, I get this error. 
Is the link which is constructed [in this line](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/compile#L221), valid and working? 

(We are not using a customized fork of this repo.)

**Comment by tugrulcan** [comment]
The links are valid but I still get the same error. 
When I try to download the file manually by running the same curl command, it can download the file downloaded properly.  But if I run the command `heroku builds:create`, it fails due to same error.

Do you think that problem is related with [Composer's new release](https://github.com/composer/composer/releases)?

**Comment by LoveMyData** [comment]
Looks like the issue resurface
https://github.com/heroku/heroku-buildpack-php/issues/251

**Comment by tugrulcan** [comment]
After upgrading the version in Heroku to v148 admin panel the problem has solved.
