### ISSUE TITLE
Failing to add cURL to OAuth request engine support

### ISSUE THREAD

**Issue by saintybalboa** [heroku/heroku-buildpack-php#322]
Hey guys,

I have an issue where PHPs oAuth extension doesn't pickup cURL as a request engine. I'm sure (based on the same issue experienced with my Ubuntu docker image) the following packages need to be installed:

```
libcurl4-gnutls-dev
libpcre3-dev
```

I've also added my query to stackoverflow:
https://stackoverflow.com/questions/54555699/heroku-adding-curl-to-oauth-request-engine-support 

Any help would be much appreciated.

cheers,

Marty

**Comment by dzuelke** [comment]
Thanks for your report! It looks like the oauth extension is somehow not picking up the presence of `libcurl` during builds on the heroku-18 stack; it works on heroku-16. That library is, of course, there; must be a headers thing. I'll investigate.

**Comment by dzuelke** [comment]
This is an oauth extension configure script bug. `config.m4` looks for `easy.h` in two hard-coded locations:

```
  AS_IF([test "x$with_curl" != "xno"],
      [
        AC_MSG_CHECKING(for cURL in default path)
        have_curl=no
        for i in /usr/local /usr; do
          if test -r $i/include/curl/easy.h; then
 ```

but on Ubuntu 18 (and Debian 9), they are in `/usr/include/x86_64-linux-gnu/curl/easy.h`.

PHP bug report has been open for a while: https://bugs.php.net/bug.php?id=76722

The solution will be for oauth to use `pkg-config` to determine the headers location.

**Comment by dzuelke** [comment]
Fix will land tomorrow together with other PHP runtime updates! If it's urgent in the meantime, `heroku stack:set heroku-16` your app.

**Comment by saintybalboa** [comment]
Thanks, appreciate the help and quick response. I’ll hang back for the new release.
