### ISSUE TITLE
Document root issues

### ISSUE THREAD

**Issue by LordKa0S** [heroku/heroku-buildpack-php#326]
I have a PHP app on heroku, which was deployed without issues as the following repository structure:

```
myapp
├── connect.php
├── elec.php
├── index.php
└── key.php
```
I cloned the app on a different machine, and reorganised the app as follows:

```
myapp
├── auth-server
│   ├── composer.json
│   ├── connect.php
│   ├── elec.php
│   ├── index.php
│   └── key.php
├── poll-server
└── Procfile
```
with the Procfile containing the following:

> web: vendor/bin/heroku-php-apache2 auth-server/

However, the deployement fails with the following message:

> Enumerating objects: 35, done.
> Counting objects: 100% (35/35), done.
> Delta compression using up to 4 threads
> Compressing objects: 100% (29/29), done.
> Writing objects: 100% (34/34), 58.78 KiB | 2.35 MiB/s, done.
> Total 34 (delta 7), reused 0 (delta 0)
> remote: Compressing source files... done.
> remote: Building source:
> remote:
> remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/php.tgz
> remote:
> remote:  !     ERROR: Application not supported by this buildpack!
> remote:  !
> remote:  !     The 'heroku/php' buildpack is set on this application, but was
> remote:  !     unable to detect a PHP codebase.
> remote:  !
> remote:  !     A PHP app on Heroku requires a 'composer.json' at the root of
> remote:  !     the directory structure, or an 'index.php' for legacy behavior.
> remote:  !
> remote:  !     If you are trying to deploy a PHP application, ensure that one
> remote:  !     of these files is present at the top level directory.
> remote:  !
> remote:  !     If you are trying to deploy an application written in another
> remote:  !     language, you need to change the list of buildpacks set on your
> remote:  !     Heroku app using the 'heroku buildpacks' command.
> remote:  !
> remote:  !     For more information, refer to the following documentation:
> remote:  !     https://devcenter.heroku.com/articles/buildpacks
> remote:  !     https://devcenter.heroku.com/articles/php-support#activation
> remote:
> remote:
> remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
> remote:
> remote:  !     Push failed
> remote: Verifying deploy...
> remote:
> remote: !       Push rejected to myapp.
> remote:
> To https://git.heroku.com/myapp.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/myapp.git'

Since I have both, index.php and composer.json, at the document root specified by the Procfile, the error message does not seem to provide accurate information on what's missing.

Further, I checked out the commit that worked on the previous machine (which is also the current deployed version) only to find it now failing with the same message as above.

**Comment by dzuelke** [comment]
`composer.json` etc need to be in the document root. This is a requirement of all buildpacks. The document root is independent of any of this.

You could, just as one approach, use `git subtree push --prefix auth-server heroku master` to push a subdir only.

**Comment by LordKa0S** [comment]
> `composer.json` etc need to be in the document root. This is a requirement of all buildpacks. The `Procfile`, and specifically for PHP the document root, is independent of any of this.
> 
> You could, just as one approach, use `git subtree push --prefix auth-server heroku master` to push a subdir only.
Thanks for the quick reply.
From what I read up about the Procfile on the devcenter, shouldn't it allow for the index.js to be in myapp/auth-server/ ? Would it work if I kept composer.json in myapp/ and index.js in myapp/auth-server/ ?

**Comment by LordKa0S** [comment]
> > `composer.json` etc need to be in the document root. This is a requirement of all buildpacks. The `Procfile`, and specifically for PHP the document root, is independent of any of this.
> > You could, just as one approach, use `git subtree push --prefix auth-server heroku master` to push a subdir only.
> 
> Thanks for the quick reply.
> From what I read up about the Procfile on the devcenter, shouldn't it allow for the index.js to be in myapp/auth-server/ ? Would it work if I kept composer.json in myapp/ and index.js in myapp/auth-server/ ?

Leaving this here for anyone that comes looking. Just verified that it does work. My new directory structure is as follows:

```
myapp
├── auth-server
│   ├── connect.php
│   ├── elec.php
│   ├── index.php
│   └── key.php
├── composer.json
├── poll-server
└── Procfile
```

**Comment by dzuelke** [comment]
What's in your `Procfile` has nothing to do with how a buildpack detects the application type (think about it, you could have "mycustomboot.sh" in there that's somehow dynamic, so how would we then figure out your document root?). All languages are the same, whether it's `requirements.txt`, `pom.xml`, `package.json`, `composer.json` or `Gemfile`: they must be at the root of the source tree.
