### ISSUE TITLE
Build Failing?

### ISSUE THREAD

**Issue by lorkel** [heroku/heroku-buildpack-php#332]
I'm getting a build error when spinning up a new instance... I have both composer.json and Procfiles that are duplicated from some of my other instances on Heroku. Looks like an ImageMagick issue possibly? 

It looks like the build is failing globally:
[https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-php](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-php)

Error log below.

`-----> ImageMagick app detected`
`-----> Grabbing env variables from argument 3`
`-----> Install ImageMagick`
`/app/tmp/buildpacks/16be109e18b3106c5af2c04ee4bf47504a4b3144b3d333645b0c543610117ebcb844242dd2e791042095a7fd35bef7fd09fb32f1b6aca8888da76de1bb7ebe27/bin/compile: line 37: php-config: command not found`
` !     Push rejected, failed to compile ImageMagick app.`
` !     Push failed`

**Comment by dzuelke** [comment]
That's not the PHP buildpack you're using there that's failing ("`ImageMagick app detected`"). Some ImageMagick thing, but you really shouldn't be needing that, given how `ext-imagick` is available by default, and the Heroku stacks have reasonably up-to-date `libmagick…` libraries.
