### ISSUE TITLE
H18 error for recent buildpack versions.

### ISSUE THREAD

**Issue by audiorecorder** [heroku/heroku-buildpack-php#342]
When uploading a file, H18 error occurs after 20 seconds.
In previous versions, this did not happen, but it has been happening since April.
Simply upload a large file that takes more than 20 seconds.
``````
<form action="./index.php" method="post" enctype="multipart/form-data">
<input type="file" id="fileload1" name="files[]">
<button type=submit>submit</button>
</form>
``````
Outside the US location, It's hard to upload 5 megabytes. It's failed to upload due to H18 error.
The only workaround is to roll back slug from the Heroku dashboard to the January or last year version. 
but can not modify the source anymore.

How do I set up the old PHP buildpack?
set https://github.com/heroku/heroku-buildpack-php.git#v146 in ".buildpacks"
It's failed to compile. Can not use the old version. I want to use old nginx, apache versions.
Please help~

**Comment by dzuelke** [comment]
Confirmed, thanks. It's a bug in HTTPD 2.4.39: https://bz.apache.org/bugzilla/show_bug.cgi?id=63325

**Comment by audiorecorder** [comment]
Thanks for reply.
When will the build pack be fixed?
Do I have to wait for a new Apache version?
What about changing from a build pack to the old stable Apache version? There is not a big problem with the old version...

**Comment by dzuelke** [comment]
We'll work around it with an explicit config for 2.4.39. That change will be rolled out today or tomorrow.

**Comment by dzuelke** [comment]
Shipped: https://devcenter.heroku.com/changelog-items/1651
