### ISSUE TITLE
Symfony 4 routing: only `/` page is working

### ISSUE THREAD

**Issue by Kr4v3N** [heroku/heroku-buildpack-php#344]
Hi everybody,

When I deploy my "symfony 4.3.1" application to Heroku,
only the / page (route) is working.
Any other routes show the Not Found error.
My Procfile file :  
`web: $(composer config bin-dir)/heroku-php-apache2 public/`

apache-pack package is installed

Any ideas on how to solve this one?

**Comment by dzuelke** [comment]
If it's not working, then `apache-pack` is not installed. I just tested and verified. You can do a `heroku run -- ls -la public/` to check if the `.htaccess` is there.

**Comment by Kr4v3N** [comment]
Thanks
