### ISSUE TITLE
Support for which php binary to use

### ISSUE THREAD

**Issue by ian** [heroku/heroku-buildpack-php#372]
OSX has the wonderful caveat that it comes preinstalled with an older version of PHP.  Although I've got 7.3 installed the `./vendor/bin/heroku-php-apache2` command seems to always use the `/usr/bin/php` version.

No matter what $PATH order I try this always seems to be the case.  How do you change the binary which is used to run PHP?

**Comment by dzuelke** [comment]
It ultimately runs `php-fpm`, not `php`, and that's typically located in `…/sbin`, not `…/bin`, so you need to fix your `$PATH` accordingly. A simple `which php-fpm` on your terminal is enough to verify.
