### ISSUE TITLE
buildpacks.io pack results in image with PHP outside of path

### ISSUE THREAD

**Issue by fuel-wlightning** [heroku/heroku-buildpack-php#373]
### Problem:
When using buildpacks.io's pack command [1] to deploy a simple php app[2] the php executable cannot be found.

Running `pack run --builder heroku/buildpacks` on the simple php app[2] results in the following output for the run section.

```
vendor/bin/heroku-php-apache2: line 260: php: command not found
This program requires PHP 5.5.11 or newer; check your 'php' command.
ERROR: run container: failed with status code: 1
```

### Workaround:

Adding a layer to the output image that runs the following commands as root allows the image to work:
```
rm -rf /home/heroku
ln -s /workspace /home/heroku
ln -s /workspace /app
```

### References:

1. pack version v0.5.0 (git sha: c9cfac75b49609524e1ea33f809c12071406547c) installed on macOS catalina via homebrew.
2. Simple php app: https://github.com/kassah/buildpackphpfail-repro

### Context

This was discussed briefly on buildpacks.io slack:
https://buildpacks.slack.com/archives/C94UJCNV6/p1573598283079300

**Comment by dzuelke** [comment]
The export at boot time is `export PATH=$HOME/.heroku/php/bin`, that seems to be the issue here.

But even if that gets fixed and hard-coded to `export PATH=/app/.heroku/php/bin`, it still won't fix the problem I think, because PHP is built with `--prefix=/app/.heroku/php`, and not relocatable, so if it resides in `/workspace` or some other location, it won't work properly (not find INIs, extensions, etc).

**Comment by fuel-wlightning** [comment]
Fixed by release of: https://github.com/heroku/pack-images/commit/cd39a89fba1a208b5993b4a5a1ed4529f6f50df1

**Comment by fuel-wlightning** [comment]
Here are the files from the above git repo since I'm deleting the repo.

public/index.php
```
<?php phpinfo(); ?>
```

Procfile:
```
web: vendor/bin/heroku-php-apache2 public/
```

composer.json
```
{
    "name": "williamlightning/test",
    "description": "Small app to test out buildpacks.",
    "type": "project",
    "require": {
        "php": "^7.0.0"
    }
}
```

composer.lock:
```
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "7edee13aca9e4a9a2fb96e459e17992a",
    "packages": [],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": {
        "php": "^7.0.0"
    },
    "platform-dev": []
}
```

**Comment by fuel-wlightning** [comment]
To test the above using the pack cli command (the pack run command can't pass runtime env PORT numbers)
```
pack build --builder heroku/buildpacks issue373
docker run -p 3000:3000 -e PORT=3000 issue373
```
