### ISSUE TITLE
Configuring memory limit for workers

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#374]
Currently, I don't think there is a way to configure a different memory limit for web dynos and worker dynos. But this would be a great feature, given we have different needs:

- for web dynos, you want to keep the memory limit low (but still enough for the needs of the application), to allow for concurrency at the PHP-FPM level. The buildpack will properly guess the number of PHP-FPM workers based on the configured memory limit and on the dyno size.
- for worker dynos, the optimal solution would be to have the memory limit equal to (or close to, in case keeping a bit of extra memory for something else makes sense) the dyno memory, as there is only one process running.

For now, I configured my Procfile to use `php -d memory_limit=512M bin/console ...` to override the memory limit of the php.ini when running the worker. But this does not adapt automatically when scaling the dyno to bigger sizes.

An idea I have would be that the buildpack exposes an env variable with the guessed worker memory limit, that could be used in such command (or a script returning it, to use it as ``php -d memory_limit=`vendor/bin/heroku-buildpack-worker-memory-limit` bin/console`` if that's easier).

What do you think about that @dzuelke ?

**Comment by dzuelke** [comment]
Funny, I'm working on this exact thing right now, and the plan is to roll out the change together with PHP 7.4. I wanted to just make the CLI `memory_limit` equal to the dyno RAM quota. Does that sound reasonable @stof?

**Comment by stof** [comment]
yes, that sounds like a good idea.
