### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by sylvaindeloux** [heroku/heroku-buildpack-php#376]
When adding `"php": "^7.4"` to composer.json, the build fails (using `web: vendor/bin/heroku-php-nginx`):

    composer.json/composer.lock requires php ^7.4 -> no matching package found.

**Comment by dzuelke** [comment]
Yes. It's not rolled out on Heroku yet. It's the Black Friday and Cyber Monday weekend, so we're obviously not making any changes, in particular not such a major one that could incur app downtime for customers with untested apps and open version requirement ranges.

Second or third week of December is currently the plan. Like always, the [changelog](https://devcenter.heroku.com/changelog) will list all updates as they happen.

**Comment by robinwo** [comment]
Any update on this guys? Have a release pending which depends on PHP 7.4 support. 😅

**Comment by dzuelke** [comment]
We've had to move it to January, sorry. There's just too little time with the holidays and everything, we have a bunch of production change freezes in place around this time.

**Comment by asgrim** [comment]
> we have a bunch of production change freezes in place around this time.

Makes sense, it is winter after all.... 😅

**Comment by romainnorberg** [comment]
please 😄

**Comment by c990802** [comment]
Hello, what is your current ETA for releasing the support for php 7.4? thanks.

**Comment by Monamoxie** [comment]
We need support for PHP 7.4. This delay is getting too far. Kindly treat as urgent

**Comment by defrl** [comment]
Still not added?

**Comment by Tyldar** [comment]
Dear Heroku devs, we definitely need it, please add it 🙏

**Comment by sylvaindeloux** [comment]
Any news about this update?
I have a deploy waiting since… end of november… 😅

**Comment by sylvaindeloux** [comment]
@dzuelke Is this more complex than expected?

**Comment by AdaptCharm** [comment]
@dzuelke Any update on this one? I just tried to upgrade from PHP 7.3 to PHP 7.4, received the same error message above.

I need PHP 7.4 so that I can implement preloading to my app.

**Comment by sylvaindeloux** [comment]
PHP 7.4.2 has been released, and we're still waiting 😂

https://www.php.net/archive/2020.php#2020-01-23-1

**Comment by pierre-le** [comment]
+1 on this one.
And guys at Heroku, we do understand you may have other priorities to handle, but a quick update would be greatly appreciated :)

**Comment by Raerten** [comment]
7.4 branch brought great language features and many composer packages require that version.
so long update is not user friendly. 
can you give us a real time frame? @dzuelke

**Comment by jonathanbuyck** [comment]
> Yes. It's not rolled out on Heroku yet. It's the Black Friday and Cyber Monday weekend, so we're obviously not making any changes, in particular not such a major one that could incur app downtime for customers with untested apps and open version requirement ranges.
> 
> Second or third week of December is currently the plan. Like always, the [changelog](https://devcenter.heroku.com/changelog) will list all updates as they happen.

For me it's an inadmissible answer. As a PaaS, Heroku should always provide the latest version of packages/utilities, as soon as possible (even beta/RC in my opinion). This is the responsability of developers to ensure the good range of the version they need in the project manifest. Open range in manifest is irresponsible and you're not reponsable of this. You're responsability is provide the latest tools despite unconscious developers.

**Comment by sylvaindeloux** [comment]
According to Heroku support:

> Will will be offering support for PHP 7.4 sometime next month. Please check our [changelog](https://devcenter.heroku.com/changelog) for any updates.

**Comment by dzuelke** [comment]
Soon, fans, soon. #385 is almost ready for roll-out.

Once that's done, I'll also take a few minutes and respond to a few of the comments on this ticket.

**Comment by AdaptCharm** [comment]
> Soon, fans, soon. #385 is almost ready for roll-out.
> 
> Once that's done, I'll also take a few minutes and respond to a few of the comments on this ticket.

Can you explain the delay and why it has taken so long?

**Comment by boboldehampsink** [comment]
Is there anywhere we can track the progress of supporting regex in mbstring? Can't use PHP 7.4 without that

**Comment by dzuelke** [comment]
It'll be back with PHP 7.4.4, @boboldehampsink.

**Comment by dzuelke** [comment]
Just to close the loop here regarding mbstring, 7.4.3 is built against `libonig`, so regexes are now supported / cc @boboldehampsink @fobin @celorodovalho @obrassard: https://devcenter.heroku.com/changelog-items/1743
