### ISSUE TITLE
php: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RicoFactset** [heroku/heroku-buildpack-php#387]
Hello,

since the new release from yesterday and also the one from today (v170 and v171) I get the following error when building the app on heroku-18 stack:
-----> Installing platform packages...
       - php (7.4.2)
       - ext-gmp (bundled with php)
       - ext-intl (bundled with php)
       - ext-mbstring (bundled with php)
       - ext-redis (5.1.1)
php: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
php: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
-----> Installing dependencies...
 
 !     ERROR: An unknown internal error occurred.
 !     
 !     Contact Heroku Support for assistance if this problem persists.
 !     
 !     Stack trace follows for debugging purposes:
 !     583 main /tmp/buildpack_5f65824fd3d80199b28b7fae22d74436/buildpack-php-1/bin/compile
 
 !     Heroku push rejected, failed to compile Php app

In composer.lock ext-zip is only required in require-dev section which is not considered when building on Heroku. I am actually not sure where libzip.so is required. Hopefully you can assist.

Thanks
Rico

**Comment by RicoFactset** [comment]
After some debugging, lines like mcount "platform.packages.php.$($engine_r "echo ${engine^^}_VERSION;")" (where php is executed) produce these errors.

**Comment by RicoFactset** [comment]
Also line
composer --no-plugins --version 2> /dev/null | tail -n 1 | indent
produces above error message while "composer" is the following alias:

composer() {
	$engine "$(which composer)" "$@"
}

**Comment by RicoFactset** [comment]
Switching back to PHP 7.3.14 fix in composer.json build is successfull. Only with ^7.3.0 (7.4.2) it does not build.

**Comment by dzuelke** [comment]
Is this happening on the "real" Heroku, or on Dokku/Herokuish/something?

I can't reproduce this problem on the platform.

**Comment by RicoFactset** [comment]
> Is this happening on the "real" Heroku, or on Dokku/Herokuish/something?
> 
> I can't reproduce this problem on the platform.

It is a company-hosted platform based on Heroku. So no, it is not the "real" Heroku.

**Comment by dzuelke** [comment]
On Herokuish you mean? 🧐

Anyway, it's your platform that's the problem. The library is missing, you should fix that.

**Comment by RicoFactset** [comment]
> On Herokuish you mean? 🧐
> 
> Anyway, it's your platform that's the problem. The library is missing, you should fix that.

I thought so too. But actually, I tried also another project (simple one) which did not change for month apart from dependency updates and esp. the new php buildpack release is used. The app runs on heroku-16 stack whereas the other app above runs on heroku-18.

So even this app shows now the same error during build, see below. Does that mean the new buildpack release supporting PHP 7.4.2 requires libzip within the stack?

-----> Installing platform packages...
       - php (7.4.2)
       - apache (2.4.41)
       - nginx (1.16.1)
php: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
php: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
-----> Installing dependencies...
 
 !     ERROR: An unknown internal error occurred.
 !     
 !     Contact Heroku Support for assistance if this problem persists.
 !     
 !     Stack trace follows for debugging purposes:
 !     584 main /tmp/buildpack_60900b35c001938f7b59eb851b5ef188/php/bin/compile

**Comment by dzuelke** [comment]
Then you have to update both of "your stacks". Sorry, this is 100% your own problem and something your Ops team can trivially fix. PHP 7.4 no longer bundles libzip, so it's needed on the system.

I find it a bit confusing that you run your own infrastructure using building blocks you clearly are not even keeping up to date and expecting "real PaaS" level functionality and compatibility from such a solution.

**Comment by RicoFactset** [comment]
I absolutely agree! Thanks for your help! I addressed it internally.
