### ISSUE TITLE
SemVer issue with php & composer

### ISSUE THREAD

**Issue by lchachurski** [heroku/heroku-buildpack-php#391]
Hey,

It seems to me that there is a bug with PHP semver interpreter at Heroku. 

Having `        "php": "~7.3",` in `compser.json` got me `        "php": "~7.4.2",` on the server. 

https://jubianchi.github.io/semver-check/#/~7.3/7.4.2

Sorry if this is not the place to address this kind of issue.

**Comment by dzuelke** [comment]
In your link, there is a huge yellow box that explains it:

> **Composer** handles tilde constraint differently. Your constraint will translate to `>=7.3.0 <8.0.0`.
>
> Given the constraint you entered, you will get:
> - The next **minor** releases which will provide **new features**
> - The next **patch** releases which will **fix bugs**

Also documented at https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
