### ISSUE TITLE
can't find mbstring 

### ISSUE THREAD

**Issue by sherif807** [heroku/heroku-buildpack-php#395]
can anyone help. 

![image](https://user-images.githubusercontent.com/8910175/75583128-07e15680-5a3b-11ea-9364-521edc95ca92.png)

**Comment by amustaine** [comment]
I have the same issue

**Comment by amustaine** [comment]
Looks like something is broken there  - https://github.com/heroku/heroku-buildpack-php/pull/394

**Comment by nemanjan00** [comment]
Quicj fix should be to set buildpack to https://github.com/heroku/heroku-buildpack-php#171

**Comment by sherif807** [comment]
any help any body?

**Comment by estrados** [comment]
me too

**Comment by sherif807** [comment]
Healthcare Blocks hosting helped me actually with this.

just add a new file on your root directory called "Aptfile" <-- capital A
with this content 

libonig-dev
libonig4

commit and deploy, worked for me with php 7.4

**Comment by dzuelke** [comment]
This is an issue with your Herokuish, Dokku, whatever environment.

If you're using this buildpack with your own infrastructure, you must ensure that you're keeping your systems up to date. We cannot provide support for your custom configurations.

**Comment by danabrey** [comment]
Anybody experiencing this issue, the fix is to add the `apt` buildpack and install the missing packages, as described here: https://github.com/gliderlabs/herokuish/issues/529#issuecomment-592938477
