### ISSUE TITLE
Sqreen 1.19.x support for PHP 7.4

### ISSUE THREAD

**Issue by paul-thebaud** [heroku/heroku-buildpack-php#399]
Hi,

When I try to build a project on Heroku with `"php": "7.4.*"` and `"ext-sqreen": "*"`, it tells me there is no version of `ext-sqreen` compatible with PHP 7.4.
But `ext-sqreen` version 1.19 is listed by composer, and according to the sqreen documentation, it is fully compatible with PHP 7.4 (check out https://docs.sqreen.com/php/release-notes/).

Is this normal? Can you fix it and make `ext-sqreen` available for PHP 7.4?

Thanks.

**Comment by dzuelke** [comment]
Please direct this question to Sqreen support. It's their extensions repository, so they have to add their 7.4 releases to it for installation (they're currently missing).

**Comment by paul-thebaud** [comment]
OK, i'll do that. Thanks.
