### ISSUE TITLE
phpunit is not working properly for automated deployments

### ISSUE THREAD

**Issue by sotoz** [heroku/heroku-buildpack-php#401]
Hello,

Phpunit in `bin/test` has [no folder](https://github.com/heroku/heroku-buildpack-php/blob/fd5ac6063236102038d06f91b938b62b6e60080f/bin/test#L46) specified for running the tests. Therefore it just exits with the phpunit help parameters as output as this is the default behaviour if you run phpunit without parameters.

This creates issues in automatic deployments for example in Gitlab's Auto-DevOps ([AutoTest](https://docs.gitlab.com/ee/topics/autodevops/index.html#auto-test))

**Comment by dzuelke** [comment]
Please use `phpunit.xml` to configure your test suite locations; see https://phpunit.readthedocs.io/en/9.5/organizing-tests.html#composing-a-test-suite-using-xml-configuration and https://phpunit.readthedocs.io/en/9.5/configuration.html#the-testsuite-element for instructions.
