### ISSUE TITLE
Error in v174

### ISSUE THREAD

**Issue by FilipLukac** [heroku/heroku-buildpack-php#406]
Hello,

We haven't changed anything in our code-base and after deploy to production with newest version of buildpack, it says (we are unable to deploy a new version):

```
remote: [1G    httpd: Syntax error on line 141 of /app/.heroku/php/etc/apache2/httpd.conf: Cannot load libexec/mod_ssl.so into server: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /app/.heroku/php/libexec/mod_ssl.so)     
remote: [1G    This program requires Apache 2.4.10 or newer with mod_proxy and mod_proxy_fcgi enabled; check your 'httpd' command.
```

COMPOSER:

```
"require": {
		"php": "~7.2.0",
		"ext-mbstring": "*",
		"ext-pdo_sqlite": "*",
		"ext-bcmath":"*",

		"nette/application": "^2.4.0",
		"nette/bootstrap": "^2.4.0",
		"nette/caching": "^2.5.0",
		"nette/component-model": "^2.3.0",
		"nette/database": "^2.4.0",
		"nette/deprecated": "^2.3.0",
		"nette/di": "^2.4.0",
		"nette/finder": "^2.4.0",
		"nette/forms": "^2.4.0",
		"nette/http": "^2.4.0",
		"nette/mail": "^2.4.0",
		"nette/neon": "^2.4.0",
		"nette/php-generator": "^2.4.0",
		"nette/reflection": "^2.4.0",
		"nette/robot-loader": "^2.4.0",
		"nette/safe-stream": "^2.3.0",
		"nette/security": "^2.4.0",
		"nette/tokenizer": "^2.2.0",
		"nette/utils": "^2.4.0",
		"latte/latte": "^2.4.0",
		"tracy/tracy": "^2.4.0",
		"dg/adminer-custom": "~1.6",
		"kdyby/console": "~2.7.0",
		"kdyby/doctrine": "~3.3.0-rc.1",
		"kdyby/events": "~3.1.0",
		"zenify/doctrine-migrations": "~2.3.0",
		"kdyby/translation": "dev-master",
		"phpseclib/phpseclib": "^2.0",
		"ublaboo/datagrid": "~5.6.0",
		"drahak/restful": "dev-master#2bccb7207a195c3e5f1aa3f59d878177e37ef1d6",
		"firebase/php-jwt": "^4.0",
		"mandrill/mandrill": "^1.0",
		"drewm/mailchimp-api": "^2.4",
		"stichoza/google-translate-php": "^3.2",
		"oro/doctrine-extensions": "^1.2",
		"markrogoyski/math-php": "^0.36.0",
		"aws/aws-sdk-php": "^3.38",
		"uestla/recaptcha-control": "^7.0",
		"mailgun/mailgun-php": "^2.6",
		"php-http/curl-client": "^1.7",
		"guzzlehttp/psr7": "^1.4",
		"google/apiclient": "^2.0",
		"lesstif/php-jira-rest-client": "^1.33",
		"guzzle/guzzle": "^3.9",
		"mashape/unirest-php": "^3.0",
    "ext-json": "*"
```

Procfile
```
web: vendor/bin/heroku-php-apache2 -C apache.conf -i php.ini www/
```

**Comment by FilipLukac** [comment]
UPDATE:
I fixed it by using additional buildpack https://github.com/heroku/heroku-buildpack-apt
then createing `Aptfile` in the root of the project and fulfill it with:

```
libonig-dev
libonig4
libssl-dev # this was the problem
```

Apparently, buildpacks doesn't have libssl module

**Comment by Petrucheqa** [comment]
Same problem using dokku with that buildpack.

**Comment by dzuelke** [comment]
Alright so this keeps happening for people using Dokku, Herokuish, etc, and the answer, as always, is the same: you chose to run your own infrastructure, so you must keep your infrastructure up to date.

That new HTTPD version was built on a system with OpenSSL 1.1.1 (which Heroku's `heroku-18` base image updated to months ago), and you're still running OpenSSL 1.1.0, which in certain edge cases can cause this problem.

There is nothing we can do to prevent this. We have to have the latest packages, in sync with upstream Ubuntu, on our systems. Code must be built in these environments. We can't build code against library versions that are no longer there.

If you chose not to run your code on Heroku, but you want to use Heroku's open source components in your own environment, then you must ensure that you keep all aspects of your infrastructure in sync.

Alternatively, you can build all PHP, web server, extension etc binaries yourself, on your own environment, and host it all on your own S3 bucket. The instructions for how to do this are included in this repository.

Either way, it's entirely your responsibility.
