### ISSUE TITLE
Support PCov extension (so we all get fast code-coverage!)

### ISSUE THREAD

**Issue by beNjiox** [heroku/heroku-buildpack-php#415]
https://github.com/krakjoe/pcov is awesome.

It's a self contained CodeCoverage compatible driver for PHP7

It removes the complexity (and slowness) of getting involved with XDebug while allowing all of us to get code coverage along with our HerokuCI builds.

🙏

**Comment by beNjiox** [comment]
Thanks so much @dzuelke !
I'll write on how to set this up once I'll do it on my projects, will help a lot of folks.

You rock!

**Comment by dzuelke** [comment]
✌️ https://devcenter.heroku.com/changelog-items/1816

Also remember that you can specify that extension in `require-dev` and then it'll only be installed for CI, not for runtime!
