### ISSUE TITLE
php-fpm: command not found

### ISSUE THREAD

**Issue by carltondickson** [heroku/heroku-buildpack-php#420]
Trying to run `heroku local` but getting an error about php-fpm command not found.

I have php-fpm7.2, php-fpm7.3 and php-fpm7.4 but it's right that php-fpm isn't a recognised command on my system

I've tried to create an alias to reference a specific version as well as configure the command on the CLI to reference the php-fpm.conf. When I created the alias php-fpm -v results in output but with -n I get

```
$ heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
15:28:48 web.1     |  vendor/bin/heroku-php-nginx: line 289: php-fpm: command not found
15:28:48 web.1     |  This program requires PHP 5.5.11 or newer; check your 'php-fpm' command.
[DONE] Killing all processes with signal  SIGINT
15:28:48 web.1     Exited with exit code null
```

Just wanted to understand if there's anything else I can try so that the script is able to successfully run a php-fpm command.

Am on Ubuntu 20 by the way

**Comment by dzuelke** [comment]
The summary unfortunately is: it's not possible at this time, see #55 :/
