### ISSUE TITLE
Output to file does not work in CLI

### ISSUE THREAD

**Issue by tbcshifter** [heroku/heroku-buildpack-php#423]
I'm running the following Procfile:

`web: vendor/bin/heroku-php-apache2 -v -l /tmp/stdout.log -F fpm_custom.conf dist/`

If I run a script in the web browser:

`file_put_contents('/tmp/stdout.log', 'stdout.log: test log data', FILE_APPEND);`

That reaches the logs.

If I run the same script via command line:

`heroku run php ~/dist/test.php`

Nothing is logged at all or output in the console.

Is this a permission issue with the CLI vs FPM worker?

However, if I run this within the script running from a web browser

`exec(PHP_BINDIR . "/php ".__DIR__."/test2.php >>/tmp/stdout.log 2>&1 &");`

The output from the `test2.php` script reaches the logs.

But again if I run this same script from the CLI, the output from `test2.php` does not appear anywhere.

**Comment by edmorley** [comment]
@tbcshifter Hi! David (the buildpack maintainer) is out at the moment, but I'll try to answer in the meantime.

The buildpack's support for apps with legacy logging is implemented in the web server wrapper scripts themselves (such as `vendor/bin/heroku-php-apache2`):
ttps://devcenter.heroku.com/articles/php-logging#adding-logging-for-legacy-applications

As such if PHP is invoked directly without using those wrapper scripts, the feature is bypassed.

I would try moving to [12-factor style logging](https://12factor.net/logs) that avoids use of a log file: https://devcenter.heroku.com/articles/php-logging
(For example logging to the file `"php://stderr"`)

**Comment by tbcshifter** [comment]
Thanks for the heads up. Logging to `stdout`/`stderr` in the script via CLI does indeed work. Unfortunately I'm implementing a worker queuing script, so the script needs to run another script as a background task from `exec()`, which requires redirecting the output to a file and I want that output to reach the logs. I can't run it from the web browser because of Heroku's routing timeout. Only CLI scripts can run indefinitely. It seems there is no solution to get the `exec()` output into the logs. I wish Heroku supported redirect to a log socket or some such device that automatically collected into the logs.

**Comment by dzuelke** [comment]
So the reason here is that you're doing the "log follow" in your `web` container, but your `heroku run` is executed in a separate, isolated container - they don't share a file system or anything else (try `heroku run rm -rf *` on a running app ;) ).

Sounds like you want `heroku run -- 'touch /tmp/stdout.log; tail -f /tmp/stdout.log & php ~/dist/test.php'` instead?

Or maybe you can `proc_open()` instead of `exec()` and just forward/grab the pipelines to the parent correctly? Pretty sure the Symfony Subprocess component also does that more or less out of the box.

**Comment by dzuelke** [comment]
(also, I am assuming you have this worker/job thing as a `Procfile` entry, but if it's really a one-off `heroku run`, you might want to use `heroku run:detached` instead)

**Comment by tbcshifter** [comment]
Thanks. I think that command might work. What I ended up doing since I am using Papertrail for logging anyway is just configure these scripts to log directly to Papertrail via UDP. Then I didn't have to change anything with the setup and don't have to worry about how to get them into Heroku's log aggregation.
