### ISSUE TITLE
Use X-Forwarded-Host for SERVER_NAME?

### ISSUE THREAD

**Issue by gnowland** [heroku/heroku-buildpack-php#435]
Hi y'all - 
Having trouble where my server is behind a proxy and the `SERVER_NAME` constant is returning the host ip address instead of the domain, which is in `HTTP_X_FORWARDED_HOST`.

I noticed there was a "#TODO" about this 
https://github.com/heroku/heroku-buildpack-php/blob/c12b3e29144e5732c863982fc08f03fbcf22ba06/conf/nginx/heroku.conf.php#L49
but it was removed in https://github.com/heroku/heroku-buildpack-php/commit/596cf90ecc139c47864afda9244b6d427fd9cc10 in favor of setting `fastcgi_param SERVER_NAME $host;`. I was wondering if you could point me in the right direction in order to use `X-Forwarded-Host` as (or instead of) `$host` for the `SERVER_NAME`.

I think https://github.com/heroku/heroku-buildpack-php/issues/49#issuecomment-43539010 might be related, but I'm not sure how to "read those values from X-Forwarded-Host and X-Forwarded-Port" because the $_SERVER["SERVER_NAME"] code is in core WordPress. Thank you.

**Comment by gnowland** [comment]
@dzuelke after extensive debugging I've determined that it is without a doubt https://github.com/heroku/heroku-buildpack-php/blob/caa1d9171f3b3a88b31e81dc303066a77b9871c6/conf/nginx/heroku.conf.php#L40 that is causing this undesired behavior -- how do I pass the `X-Forwarded-Host` as `$host` in order to achieve the desired behavior?

**Comment by gnowland** [comment]
I have successfully overridden this behavior with the following `nginx.inc.conf` included using a `Procfile` command of `web: heroku-php-nginx -C nginx.inc.conf`:

```
location ~ \.php {
  include fastcgi_params;

  fastcgi_split_path_info ^(.+\.php)(/.*)$;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  # try_files resets $fastcgi_path_info, see http://trac.nginx.org/nginx/ticket/321, so we use the if instead
  fastcgi_param PATH_INFO $fastcgi_path_info if_not_empty;
  # pass actual request host instead of localhost
  fastcgi_param SERVER_NAME sub.domain.tld;

  if (!-f $document_root$fastcgi_script_name) {
    # check if the script exists
    # otherwise, /foo.jpg/bar.php would get passed to FPM, which wouldn't run it as it's not in the list of allowed extensions, but this check is a good idea anyway, just in case
    return 404;
  }

  fastcgi_pass heroku-fcgi;
}
```
 Is this the best/only way to do this? I assume it's not very forward-compatible....

**Comment by dzuelke** [comment]
This is not on Heroku, right? Because there is no `X-Forwarded-Host` header there; the router sends the original host in the `Host` header.

AWS ELBs, CloudFlare etc do the exact same thing.

Maybe you can also configure your proxy that way.

**Comment by gnowland** [comment]
Right, it's [herokuish](https://github.com/gliderlabs/herokuish). The strange thing is that the NGINX proxy is sending the original host in the `Host` header, not sure where it's being overridden within the container. I've got to move on with other pressing matters but will take a look back at this when I've got some more time. Thanks for your response.
