### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by mathieutu** [heroku/heroku-buildpack-php#441]
Hi, 
As the experience showed us that an Heroku implementation of a new php relase can take a while, I'm raising this issue to announce that PHP8 will be release on 26 november, and it brings a lot of features, so it could be cool to have it as soon as possible.

As usual, please tell us if we can help in any way.

Thanks.

**Comment by dzuelke** [comment]
```ShellSession
$ git push heroku main
…
remote: -----> PHP app detected
remote: -----> Bootstrapping...
remote:        NOTICE: Default platform repository disabled.
remote:        NOTICE: Bootstrapping using [REDACTED]...
remote: -----> Installing platform packages...
remote:        - php (8.0.0RC2)
remote:        - apache (2.4.46)
remote:        - nginx (1.18.0)
remote: -----> Installing dependencies...
…
 * [new branch]      main -> main

$ heroku run php -i | head -n5
Running php -i on hypertext-preprocessor-8000... up, run.6922 (Free)
phpinfo()
PHP Version => 8.0.0RC2

System => Linux 34c5ae1a-efdf-44a7-aef3-7177ee1276f4 4.4.0-1081-aws #85-Ubuntu SMP Tue Oct 6 19:47:16 UTC 2020 x86_64
Build Date => Oct 20 2020 12:31:44
```

November 26 won't be possible (Black Friday weekend freezes), but shortly after Cyber Monday is realistic.

We'll make RC3 available next week on the new heroku-20 stack for those who want to try it out.

**Comment by dzuelke** [comment]
PHP 8.0.0RC4 is now available on the heroku-20 stack, along with ext-mongodb 1.9.0RC1.

**Comment by foremtehan** [comment]
My man can you tell me when php8 will be widely available in heroku?

**Comment by dzuelke** [comment]
Release coming on Tuesday at the latest.

**Comment by mathieutu** [comment]
Thanks for the work @dzuelke!
