### ISSUE TITLE
Add ext-redis support to PHP 8

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#452]
ext-redis has been available in all previous PHP buildpacks

**Comment by dzuelke** [comment]
There is no release of `ext-redis` that works with PHP 8 yet. This is explicitly called out at https://devcenter.heroku.com/changelog-items/1959

**Comment by boboldehampsink** [comment]
Sorry, totally missed that.

**Comment by boboldehampsink** [comment]
@dzuelke I can't find why ext-redis won't work on PHP8, could you share?

**Comment by dzuelke** [comment]
Hmmh you're right, I thought it didn't build but it actually does.

Thanks for insisting ;) Will fix shortly.
