### ISSUE TITLE
ERROR: Failed to download minimal PHP for bootstrapping!

### ISSUE THREAD

**Issue by mathiasjakobsen** [heroku/heroku-buildpack-php#463]
Using `https://github.com/heroku/heroku-buildpack-php.git` as a buildpack causes the following error, using the latest version.

```sh
       =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-php.git
       =====> Detected Framework: PHP
remote: -----> Bootstrapping...
remote:
remote:  !     ERROR: Failed to download minimal PHP for bootstrapping!
remote:  !
remote:  !     This is most likely a temporary internal error. If the problem
remote:  !     persists, make sure that you are not running a custom or forked
remote:  !     version of the Heroku PHP buildpack which may need updating.
remote:
remote: ERROR: Build failed: exec: job exited with status 1
To XXXXXXXXXXX
 ! [remote rejected] master -> master (pre-receive hook declined)
```

Using `https://github.com/heroku/heroku-buildpack-php.git#v188` seems to solves the issue.

**Comment by edmorley** [comment]
@mathiasjakobsen Hi! What platform is this on? The `ERROR: Build failed: exec: job exited with status 1` line doesn't look like Heroku. Support for a few older things (including Cedar-14) was dropped from the v189 release - perhaps your platform is still using them?
https://github.com/heroku/heroku-buildpack-php/blob/main/CHANGELOG.md#v189-2021-02-05

**Comment by dzuelke** [comment]
Yeah looks like you're using Dokku, Herokuish, one of those, in an environment based on the cedar-14 stack, which is now EOL, as the upstream Ubuntu 14.04 is EOL.
