### ISSUE TITLE
apache mod_rewrite not working?

### ISSUE THREAD

**Issue by katmai** [heroku/heroku-buildpack-php#47]
hi,

i am trying to push my app with the beta buildpack, and mod rewrite doesn't seem to me working, my .htaccess is there, but i am getting a 404 error from CI when trying to rewrite the url's

any ideas?

**Comment by Bluscream** [comment]
Can't use this .htaccess file for some reason :/ https://github.com/Wruczek/ts-website/blob/1.0/.htaccess

**Comment by dzuelke** [comment]
The "some reason" can be found in `heroku logs`, because Apache will tell you what's wrong with the file!
