### ISSUE TITLE
Extension example documentation error

### ISSUE THREAD

**Issue by lletourn** [heroku/heroku-buildpack-php#477]
In
heroku-buildpack-php/support/build/README.md

Under 'Creating Custom Dockerfiles'
The FROM is
FROM formulatest-heroku-20:latest

Shouldn't it be
FROM php-heroku-20:latest

from the previous steps?

**Comment by dzuelke** [comment]
Yes it should ;)

**Comment by lletourn** [comment]
Thank you David
