### ISSUE TITLE
Bump ext-mongodb version to 1.10.0

### ISSUE THREAD

**Issue by johnwilson** [heroku/heroku-buildpack-php#495]
The current mongodb driver is at version `1.9.0` and requires `ext-mongodb: ^1.10.0`. Currently `ext-mongodb` on Heroku is at version `1.9.1`.

**Comment by dzuelke** [comment]
Yup, thanks for the reminder; it'll be rolled out next week Thursday at the very latest together with the usual PHP runtime updates.

**Comment by johnwilson** [comment]
Thanks for your time.
