### ISSUE TITLE
GD library support

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [heroku/heroku-buildpack-php#511]
When I tried to use the GD library for image acquisition, an **HTTP 500** Error was returned. And I did not find the relevant settings of the GD library in this library. I hope to be able to support the GD library.

**Comment by hjJunior** [comment]
How can I use/install GD library?

**Comment by XiaMoHuaHuo-CN** [comment]
> How can I use/install GD library?

you can use php-Composer file to add an GD requirement.
https://devcenter.heroku.com/articles/php-support
