### ISSUE TITLE
php 8.1 support

### ISSUE THREAD

**Issue by rbaarsma** [heroku/heroku-buildpack-php#521]
PHP 8.1 has been released. Would be great if we can start using it :)

**Comment by dzuelke** [comment]
We're of course aware ;) No changes to the platform around the Thanksgiving holidays, due to possible Black Friday / Cyber Monday customer impact. Just a few more days.

**Comment by dzuelke** [comment]
https://github.com/heroku/heroku-buildpack-php/pull/523
https://devcenter.heroku.com/changelog-items/2304
