### ISSUE TITLE
buildpack not detecting PHP codebase even with a composer.json file in root dir

### ISSUE THREAD

**Issue by mind-easy** [heroku/heroku-buildpack-php#535]
I have a project that is already in production on Heroku with the exact same directory structure. 
I just tried to update it but now it keeps throwing "ERROR: Application not supported by this buildpack!". 

<img width="1004" alt="Screen Shot 2022-02-04 at 4 22 29 PM" src="https://user-images.githubusercontent.com/87241372/152605044-baf29944-434d-4b46-9432-d60b4133a932.png">

The current project structure is this: 
myapp
├── composer.json
├── composer.lock
├── index.php
└── assets

I already checked and composer.lock file is git tracked.

**Comment by dzuelke** [comment]
And you're pushing the right branch (`main`? `master`?), etc?

Nothing has changed to the detection script in nearly four years. Happy to help you debug, but the problem must be on your end.
