### ISSUE TITLE
Unable to install ext-mbstring

### ISSUE THREAD

**Issue by EvilasioAnisio** [heroku/heroku-buildpack-php#539]
Hi, I'm currently maintaining a laravel 8 app on heroku and after an update today, i keep getting this error:

`Call to undefined function Illuminate\Support\mb_strimwidth()`

After diagnosing said problem, i found that adding **ext-mbstring** to composer.json would solve my issue. After doing that (composer update, git commit, etc.), checking the build log, heroku seems to fail to detect ext-mbstring and properly install it:

```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/php
-----> PHP app detected
-----> Bootstrapping...
-----> Preparing platform package installation...
-----> Installing platform packages...
       - php (8.1.2)
       - ext-gd (bundled with php)
       - apache (2.4.52)
       - composer (2.2.5)
       - nginx (1.20.2)
       - ext-exif (bundled with php)
-----> Installing dependencies...
``` 

This was not an issue before, as I can see ext-mbstring being installed on previous build logs:

```
-----> PHP app detected
-----> Bootstrapping...
-----> Preparing platform package installation...
-----> Installing platform packages...
       - php (8.1.2)
       - apache (2.4.52)
       - composer (2.2.5)
       - nginx (1.20.2)
       - ext-exif (bundled with php)
       - ext-gd (bundled with php)
       - ext-mbstring (bundled with php)
```
     
I'm at a loss as why this is happening now.

**Comment by derrickschoen** [comment]
I am having the same problem

**Comment by OscarOzaine** [comment]
Issue is currently being resolved (https://github.com/heroku/heroku-buildpack-php/pull/537#issuecomment-1035413161)

A solution for now is to install `polyfill-mbstring` with `composer require symfony/polyfill-mbstring:~1.23.1`

**Comment by dzuelke** [comment]
Hi all!

Right now, this is intentional - Composer is, finally, resolving all dependencies correctly into a minimal set for platform installs on Heroku, and since `symfony/polyfill-mbstring` is present and declaring a `provide` for `ext-mbstring`, this results in the "native" `ext-mbstring` not being installed.

There is work in flight to attempt installations for all `provide`d extensions after the main install concludes; it'll land very soon, but no promises that this will still happen this week.

In the meantime, as @OscarOzaine said, the workaround is to either:
1. `require` package `symfony/polyfill-mbstring` version `~1.23.1`, or
2. declare package `symfony/polyfill-mbstring` as `replace`d (version `*`) in the root of your `composer.json`.

This issue will update once a fix has landed.

Thanks for your patience!

**Comment by jcart** [comment]
@dzuelke Thanks for the explanation. I can confirm in our case the other dependencies are requiring the polyfill, which leads to this behaviour of missing the extension.

We are looking forward to this fix, but hope your team would give us more advance notice on potential BC issues, considering Heroku buildpacks cannot be pinned to specific versions.

**Comment by EvilasioAnisio** [comment]
> 

Hi, thanks for the heads-up! The first workaround fixed it for me. I think it would be interesting to be prompted with a message/warning for when this happens so we can understand why said package isn't being installed, i was going a bit insane trying to make this work haha. I will be marking this issue as closed.

**Comment by dzuelke** [comment]
This is now implemented in branch `composer2installer`:

```
remote: -----> Installing platform packages...
remote:        - php (8.1.2)
remote:        - apache (2.4.52)
remote:        - composer (2.2.5)
remote:        - nginx (1.20.2)
remote:        NOTICE: detected userland polyfill packages for PHP extensions
remote:        NOTICE: now attempting to install native extension packages
remote:        Installing extensions provided by symfony/polyfill-mbstring:
remote:        - ext-mbstring (bundled with php)
```

Please give it a try if you can:

```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-php.git#composer2installer
```

and report back any issues!

**Comment by alkemann** [comment]
@dzuelke I tried to set the buildpack and rerun tests, they did not install mbstring

**Comment by eithed** [comment]
Please bear in mind that `symfony/polyfill-mbstring` doesn't contain all mbstring methods.

Doing:

```
"require": {
        "php": "^8.1",
        "ext-mbstring": "*",
        ...
},
"replace": {
        "symfony/polyfill-mbstring": "*"
},
```

correctly bundles mbstring
```
-----> Installing platform packages...
       - php (8.1.2)
       - ext-intl (bundled with php)
       - ext-mbstring (bundled with php)
```

**Comment by dzuelke** [comment]
> @dzuelke I tried to set the buildpack and rerun tests, they did not install mbstring

@alkemann do you have a reproduce case? or can you open a Heroku support case so I can look at the app? Just to make sure - did you deploy a change (empty commit is probably fine), or just re-run CI?

**Comment by duffn** [comment]
> This is now implemented in branch `composer2installer`:
> 
> ```
> remote: -----> Installing platform packages...
> remote:        - php (8.1.2)
> remote:        - apache (2.4.52)
> remote:        - composer (2.2.5)
> remote:        - nginx (1.20.2)
> remote:        NOTICE: detected userland polyfill packages for PHP extensions
> remote:        NOTICE: now attempting to install native extension packages
> remote:        Installing extensions provided by symfony/polyfill-mbstring:
> remote:        - ext-mbstring (bundled with php)
> ```
> 
> Please give it a try if you can:
> 
> ```
> heroku buildpacks:set https://github.com/heroku/heroku-buildpack-php.git#composer2installer
> ```
> 
> and report back any issues!

Using this buildback installed `ext-mbstring` for me. 

```
    "require": {
        "php": "^7.3|^8.0",
        "ext-gd": "*",
        "ext-mbstring": "*",
        ...
```

```
=====> Detected Framework: PHP
remote: -----> Bootstrapping...
remote: -----> Preparing platform package installation...
remote: -----> Installing platform packages...
remote:        - php (8.1.2)
remote:        - ext-mbstring (bundled with php)
remote:        - ext-gd (bundled with php)
remote:        - apache (2.4.52)
remote:        - composer (2.2.5)
remote:        - nginx (1.20.2)
remote:        - ext-pcntl (bundled with php)
remote:        - ext-exif (bundled with php)
```

**Comment by dzuelke** [comment]
@alkemann ah, my bad, I just realized, for Heroku CI, you'd have to define the buildpack in your `app.json`.

**Comment by pedrommone** [comment]
Unfortunately Laravel needs some methods: `mb_strcut` and `mb_strimwidth`. We have built them as a helpers inside composer.

```
<?php

if (! function_exists('mb_strimwidth')) {
    function mb_strimwidth(string $string, int $start, int $width, string $trim_marker = "", ?string $encoding = null): string
    {
        return mb_strlen($string, $encoding) > $width ? mb_substr($string, $start, $width, $encoding).$trim_marker : $string;
    }
}
```

```
<?php

if (! function_exists('mb_strcut')) {
    function mb_strcut(string $string, int $start, ?int $length = null, ?string $encoding = null): string
    {
        return utf8_decode(mb_substr($string, $start, $length, $encoding));
    }
}
```

```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/Helpers/mb_strcut.php",
            "app/Helpers/mb_strimwidth.php"
        ]
    },
```

**Comment by jcart** [comment]
Thanks for the quick turnaround @dzuelke

**Comment by pedrommone** [comment]
Thanks quick solution @dzuelke! :)

**Comment by dzuelke** [comment]
Docs also here https://devcenter.heroku.com/changelog-items/2353 and here https://devcenter.heroku.com/articles/php-support#treatment-of-extensions-provided-by-userland-packages
