### ISSUE TITLE
Support new relic with php 8.1

### ISSUE THREAD

**Issue by chabior** [heroku/heroku-buildpack-php#548]
New relic released a new version with PHP 8.1 support ([here](https://github.com/newrelic/newrelic-php-agent/releases)). When do you plan to make it available on Heroku?

**Comment by dzuelke** [comment]
Apologies for not having updated this; fixed in 5bd20f4f70a30fb975235f639657c46aa4400c71 and [released on March 17th](https://devcenter.heroku.com/changelog-items/2368).
