### ISSUE TITLE
Composer fails to run on linux-arm64 os

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#590]
When running composer on ubuntu 22 with arm64 architecture, I see the following error:

`composer install --prefer-dist --no-scripts --no-progress --no-interaction --no-autoloader:
#0 0.140 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

I know that arm64 isn't officially supported, but it would be nice for me to know if anything in this buildpack is arch-specific (and why it is trying to use qemu) - or that it is my OS that is failing me

**Comment by dzuelke** [comment]
What Composer? Heroku's builds? That's not a binary; it's run using `php` due to the shebang. So you're also using Heroku's PHP, I assume?

Is this in Docker?

You have to use `FROM --platform=linux/amd64 …` or Docker will select an ARM64 image.

**Comment by boboldehampsink** [comment]
That could've been clearer, sorry. It has to do with https://github.com/heroku/stack-images/pull/227 - I'm trying to create an arm64 version of heroku stack docker images, and so far so good. This error occurs when running php/composer from this buildpack in a docker based on that arm64 heroku file. Any idea why that is? Should PHP  be compiled specifically for arm64 perhaps?

**Comment by dzuelke** [comment]
Yeah it's all compiled for only x86_64 at the moment.

**Comment by boboldehampsink** [comment]
Yeah thought so, no problem! Just trying to think of a way to make the Docker images perform on M1 macs. Its terrible atm.

**Comment by boboldehampsink** [comment]
Dohh, ofcourse you have, and very well documented as well. Apologies.
