### ISSUE TITLE
PHP 8.2.2 upgrade

### ISSUE THREAD

**Issue by erikgaal** [heroku/heroku-buildpack-php#616]
Hi there,

Our Laravel app is running into issues as reported in https://github.com/php/php-src/issues/9675. It's been fixed in 8.2.2, but that version is not yet supported on Heroku. When do we expect this version to be released?

Kind regards,

**Comment by dzuelke** [comment]
Updates will land mid-week. Thank you for your patience!

**Comment by erikgaal** [comment]
Awesome, thanks for your support!
