### ISSUE TITLE
PhalconPHP

### ISSUE THREAD

**Issue by khoan** [heroku/heroku-buildpack-php#62]
is this on the roadmap?

**Comment by marvinroger** [comment]
Anything new?

**Comment by dzuelke** [comment]
It's been forever, but it's now finally ready for rollout next week. Thanks for your patience!

**Comment by sdrib** [comment]
Excellent, that is great news!

**Comment by dzuelke** [comment]
Now available: https://devcenter.heroku.com/changelog-items/794
