### ISSUE TITLE
v232 is not published in packagist.org

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#627]
So composer update is not picking it up

**Comment by boboldehampsink** [comment]
@dzuelke tagging you in case you missed it ;-)

**Comment by dzuelke** [comment]
Thank you @boboldehampsink, I had indeed missed this.

It might take a while to untangle this. No ETA. The cause is an IP allow list that's now in place on the `heroku` GitHub org.

**Comment by boboldehampsink** [comment]
Ahh ok - you can't manually force an update on packagist.org for the time being?

**Comment by dzuelke** [comment]
Nope, not possible, it needs API access to the releases even for that.

It shouldn't be a biggie though, since nothing has changed in the "usable" part of the buildpack for a while.

**Comment by boboldehampsink** [comment]
@dzuelke any update on this?

**Comment by boboldehampsink** [comment]
Hi @dzuelke, any news?

**Comment by dzuelke** [comment]
It's working again, by the way, with all releases up there :)
