### ISSUE TITLE
Unable to deploy Symfony application 

### ISSUE THREAD

**Issue by toretto460** [heroku/heroku-buildpack-php#64]
The application cache files ( in `/app/cache/prod/` )  are full of absolute paths pointing to the temporary build directory.
For instance my `/app/cache/prod/appProdProjectContainer.php` contains a lot of this
```php
return $this->services['annotation_reader'] = new \Doctrine\Common\Annotations\FileCacheReader(
    new \Doctrine\Common\Annotations\AnnotationReader(), '/tmp/build_db41a582-b353-4a53-9ef4-837e2ccb9c62/app/cache/prod/annotations', false
);
```

I think this issue is because the `app/console cache:clear` command runs when the application code is  located to the temporary build directory.

I suppose the flow is the following:
1. Deploy the code to `/tmp/build_XXX/`
2. Run all tasks (including cache:warmup)
3. Move all the application code to `/app`

**Comment by eddiejaoude** [comment]
I think this can be closed now?
