### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by dwightwatson** [heroku/heroku-buildpack-php#664]
Hi - I know PHP 8.3 only shipped today but just wondering what the timeframe is for getting it on Heroku?

**Comment by dzuelke** [comment]
Hi! Same procedure as every year: we don't roll out the new "major" versions immediately, as they always arrive on the Thursday of a Thanksgiving weekend, and we avoid any changes to the platform until the week after (think "Cyber Monday" etc).

But packages are already built, so you won't have to wait much longer ;)

**Comment by dzuelke** [comment]
Shipped in https://github.com/heroku/heroku-buildpack-php/pull/673 / https://devcenter.heroku.com/changelog-items/2765
