### ISSUE TITLE
ext-newrelic segmentation fault, breaks site

### ISSUE THREAD

**Issue by boboldehampsink** [heroku/heroku-buildpack-php#668]
Seeing this in my release phase with the latest buildpack: 

`2023-11-30 11:27:58.144 +0000 (62 62) warning: nr_php_gather_v2_docker_id: Unable to read docker v2 container id
Segmentation fault`

**Comment by boboldehampsink** [comment]
See also https://help.heroku.com/sharing/1121b3f0-a3af-49e1-80e9-1726fb5d3167 for more context

**Comment by dzuelke** [comment]
Can't reproduce the segfault so far, but I too see the warning. Issue filed with NR: https://github.com/newrelic/newrelic-php-agent/issues/791
