### ISSUE TITLE
Upgrade New Relic Agent 11.0.0.13 => 11.0.0.14

### ISSUE THREAD

**Issue by holtkamp** [heroku/heroku-buildpack-php#750]
See Heroku ticket 1419043: an error occurs with New Relic agent 11.0.0.13 which crashes an Heroku PHP application: 
https://forum.newrelic.com/s/hubtopic/aAXPh0000005QczOAE/nr-php-agent-fatal-error

Apparently version 11.0.0.14 is released on 26-08-2024 which should fix this: https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-11-1-0-14/

**Comment by dzuelke** [comment]
Yes, we're aware; that extension update is scheduled for tomorrow, together with the usual routine PHP runtime releases!

**Comment by Zul3s** [comment]
Hello, 
We have this problem. Any new when it's update ?

**Comment by dzuelke** [comment]
https://devcenter.heroku.com/changelog-items/2980

**Comment by Zul3s** [comment]
Excellent news! Works for us again. Thanks.
