### ISSUE TITLE
Support for Compilation From Source

### ISSUE THREAD

**Issue by winmillwill** [heroku/heroku-buildpack-php#83]
It seems from the README that one should be able to maintain an S3 bucket with their own binaries, but bin/compile.sh seems to be hardcoded to use a particular bucket. Is the idea to add a check for an extant value for S3_URL and just use it straight up if it does? If so, I'll happily submit a PR, I just wanted to make sure I wasn't missing something.

The reason I ask is because I need LDAP support, and there doesn't seem to be a way to make that a separate extension -- one must compile php with ldap directives.

**Comment by stof** [comment]
See #104 about the plans for that

**Comment by djtarazona** [comment]
I needed LDAP support as well so I created a custom buildpack: https://github.com/Welkio/heroku-buildpack-php

**Comment by upendraq** [comment]
I tried  https://github.com/Welkio/heroku-buildpack-php but LDAP module is not working.

**Comment by dzuelke** [comment]
Closing in favor for the now-shipped #104.
