### ISSUE TITLE
Use CACHE_DIR for php, apache, nginx archive

### ISSUE THREAD

**Issue by phuonglm** [heroku/heroku-buildpack-php#97]
in https://github.com/heroku/heroku-buildpack-php/blob/master/bin/compile#L180 I see the code download the php archive without use the cache dir, please save the archive to CACHE_DIR first, next time we need to check the checksum and update the cache if not match.

**Comment by dzuelke** [comment]
No. This does not provide a performance benefit because the cache needs to be pulled from somewhere as well, and the cache in fact lives on S3, so it doesn't matter. I measured this a lot. All it would add is the overhead of having to maintain a manifest with checksums to allow for re-downloads.
