### ISSUE TITLE
Missing Ctype extension

### ISSUE THREAD

**Issue by RobinvdVleuten** [heroku/heroku-buildpack-php#99]
Hi there,

One of the projects I am working on, requires the [Ctype extension](http://php.net/manual/en/book.ctype.php). Is it possible to add the `--enable-ctype` flag to the build script?

Cheers,
Robin

**Comment by dzuelke** [comment]
http://php.net/manual/en/ctype.installation.php:

> Beginning with PHP 4.2.0 these functions are enabled by default.

Also:

```
$ heroku run 'php -r "ctype_alnum();"'
Running `php -r "ctype_alnum();"` attached to terminal... up, run.2195
PHP Warning:  ctype_alnum() expects exactly 1 parameter, 0 given in Command line code on line 1
```
